= Docker Compose

[source,yaml]
----
version: '3.2'

services:
  component-server: <1>
    healthcheck:
      timeout: 3s
      interval: 3s
      retries: 3
      test: curl --fail http://localhost:8080/api/v1/environment
    image: tacokit/component-server:${COMPONENT_SERVER_IMAGE_VERSION:-1.1.6_20190208104207}
    environment:
    - _JAVA_OPTIONS=
        -Djava.library.path=/opt/talend/component-kit/work/sigar/sigar:/usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/server:/usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64:/usr/lib/jvm/java-1.8-openjdk/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
        -Dtalend.component.server.filter.secured.tokens=vault-proxy <2>
        -Dtalend.component.server.ssl.active=true <3>
        -Dtalend.component.server.ssl.keystore.location=/opt/talend/configuration/https.p12 <3>
        -Dtalend.component.server.ssl.keystore.type=PKCS12 <3>
        -Dtalend.component.server.component.registry=/opt/talend/connectors/component-registry.properties <4>
        -Dtalend.component.server.maven.repository=/opt/talend/connectors <4>
    volumes:
    - connectors:/opt/talend/connectors:ro  <4>
    - vault-proxy-configuration:/opt/talend/configuration <3>


  component-server-vault-proxy: <5>
    healthcheck:
      timeout: 3s
      interval: 3s
      retries: 3
      test: curl --fail http://localhost:8080/api/v1/proxy/environment
    image: tacokit/component-server-vault-proxy:${COMPONENT_SERVER_VAULT_PROXY_IMAGE_VERSION:-1.1.6_20190208104221}
    environment:
    - _JAVA_OPTIONS=
        -Djava.library.path=/opt/talend/component-kit/work/sigar/sigar:/usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/server:/usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64:/usr/lib/jvm/java-1.8-openjdk/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
        -Dtalend.vault.cache.client.server.certificate.keystore.location=/opt/talend/configuration/https.p12 <6>
        -Dtalend.vault.cache.client.server.certificate.keystore.type=PKCS12 <6>
        -Dtalend.vault.cache.client.server.hostname.accepted=component-server <6>
        -Dtalend.vault.cache.client.server.authorization=vault-proxy <7>
        -Dtalend.vault.cache.talendComponentKit.url=https://component-server:8080/api/v1 <7>
        -Dtalend.vault.cache.vault.url=http://vault:8200 <8>
        -Dtalend.vault.cache.vault.auth.roleId=myrole <8>
        -Dtalend.vault.cache.vault.decrypt.endpoint=v1/something/decrypt/00000001 <8>
        -Dtalend.vault.cache.security.allowedIps=${COMPONENT_SERVER_VAULT_PROXY_CLIENT_IP:-127.0.0.1} <9>
    ports:
    - 9090:8080/tcp
    links: <10>
    - "component-server:component-server"
    # - "vault:vault"
    volumes:
    - vault-proxy-configuration:/opt/talend/configuration:ro

  connectors: <11>
    image: registry.datapwn.com/talend/connectors:${CONNECTORS_IMAGE_VERSION:-1.0.0_master_20190208091312}
    environment:
    - CONNECTORS_SETUP_OPTS=setup --wait-for-end
    volumes:
    - connectors:/opt/talend/connectors:ro

volumes: <12>
  connectors:
  vault-proxy-configuration:
----

<1> The standard Component Server entry
<2> Ensure only a client with a particular token can call the server (it is a kind of shared secret and only enables to call the server in "remote" mode since only local mode is enabled by default)
<3> Activates and configure the auto generation of a X.509 certificate which will be used for HTTPS connector on the server
<4> Bind as usual the components to deploy into the server
<5> This is where we will define the vault proxy service which will do the mediation between Vault and Component Server.
<6> Since both server are colocalized we inherit from the Component Server certificate to create the client which will connect on it
<7> We configure the base url to connect to the server - see <10>
<8> We configure vault connection and security informations
<9> We ensure we can connect from `$COMPONENT_SERVER_VAULT_PROXY_CLIENT_IP` to vault proxy (other IP will be rejected)
<10> We link both services to let them communicate between them, it allows to not expose the Component Server port outside its own container (no `ports` mapping in Component Server service definition). Note that if your vault is a service as well you can link it here as well.
<11> The common component image service definition (as previously)
<12> The volumes used by the services, the `connectors` one is the same as before but we added `vault-proxy-configuration` for the automatic HTTPS configuration.

This setup enables the Vault Proxy and Component Server to communicate, now you can use
the Vault Proxy as if it was the Component Server, just use `http://localhost:9090` - or any other host matching your deployment - instead of the
Component Server directly.