= Configuration mechanism

The configuration uses Microprofile Config for most entries. It means it can be passed through system properties and environment variables (by replacing dots with underscores and making the keys uppercase).

To configure a Docker image rather than a standalone instance, Docker Config and secrets integration allow you to read the configuration from files. You can customize the configuration of these integrations through system properties, as described below in this document.

Also note that Docker integration provides a `secure:` support to encrypt values when required. it also works for system properties.

== Docker Config

org.talend.sdk.component.docker.secret.config.DockerConfigConfigSource.base:: configuration location. Defaults to `/`.
org.talend.sdk.component.docker.secret.config.DockerConfigConfigSource.prefixes:: file name prefixes to take into account. Defaults to nothing, which means that all prefixes but the common UNIx exclusions are taken into account.

For example, creating a `/talend.foo.bar` file makes its content available under the `talend.foo.bar` key.

== Docker Secrets

org.talend.sdk.component.docker.secret.config.DockerSecretConfigSource:: secrets location. Defaults to `/run/secrets`.

For example, creating a `/run/secrets/talend.foo.bar` file makes its content available under the `talend.foo.bar` key.

== Secure values support

A security mechanism allows to use a ciphered value instead of a clear value for passing sensitive data (password, secret, token, etc.).

It relies on `org.talend.sdk.component.configuration.converter.secured.ConfigurationMain`, which allows you to:

1. create a `master_key` file
2. encrypt a value
3. decrypt a value (for testing purposes)

A master password is stored and obfuscated in a `master_key` file. The algorithm `AES/CBC/PKCS5Padding` ciphers the value and encodes the result in base64. This mechanism allows to manage the value as plain text and easily pass it through all potential ways you can set the configuration.

IMPORTANT: The secure values support is managed through the `org.talend.sdk.component:secured-string-converter` artifact. You can find it for released versions on link:http://repo.maven.apache.org/maven2/org/talend/sdk/component/secured-string-converter[Central].

The command examples in the sections below assume you have set the alias in your profile:

[source,sh]
----
alias tssc="java -cp secured-string-converter.jar org.talend.sdk.component.configuration.converter.secured.ConfigurationMain"
----

If it is not the case, replace `tssc` by the full command.

=== Generating the master key

To generate the master key, use the provided configuration in the `org.talend.sdk.component:secured-string-converter` artifact:

[source,sh]
----
tssc --master-key /path/to/my_master_key [secret-value]
----

IMPORTANT: Set the `talend.component.server.configuration.master_key.location` system property on the server to ensure it uses this master key. Make sure that only the applications needing this key can read it.

=== Encrypting a value

To encrypt a value, use the provided configuration in the `org.talend.sdk.component:secured-string-converter` artifact:

[source,sh]
----
tssc --encrypt /path/to/my_master_key my_credential_to_encrypt
----

=== Decrypting a value

To decrypt a value, use the provided configuration in the `org.talend.sdk.component:secured-string-converter` artifact:

[source,sh]
----
tssc --decrypt /path/to/my_master_key secure:my_credential_to_encrypt
----
