
= Dataset

Mark a model (complex object) as being a dataset.

- API: @org.talend.sdk.component.api.configuration.type.DataSet
- Sample:

[source,js]
----
{
  "tcomp::configurationtype::name":"test",
  "tcomp::configurationtype::type":"dataset"
}
----


= Datastore

Mark a model (complex object) as being a datastore (connection to a backend).

- API: @org.talend.sdk.component.api.configuration.type.DataStore
- Sample:

[source,js]
----
{
  "tcomp::configurationtype::name":"test",
  "tcomp::configurationtype::type":"datastore"
}
----


= DatasetDiscovery

Mark a model (complex object) as being a dataset discovery configuration.

- API: @org.talend.sdk.component.api.configuration.type.DatasetDiscovery
- Sample:

[source,js]
----
{
  "tcomp::configurationtype::name":"test",
  "tcomp::configurationtype::type":"datasetDiscovery"
}
----


= DynamicDependenciesServiceConfiguration

Mark a model (complex object) as being the configuration used in services annotated with @DynamicDependencies.

- API: @org.talend.sdk.component.api.configuration.type.DynamicDependenciesServiceConfiguration
- Sample:

[source,js]
----
{
  "tcomp::configurationtype::name":"test",
  "tcomp::configurationtype::type":"dynamicDependenciesServiceConfiguration"
}
----


= Checkpoint

Mark a model (complex object) as being a checkpoint configuration and state.

- API: @org.talend.sdk.component.api.input.checkpoint.Checkpoint
- Sample:

[source,js]
----
{
  "tcomp::configurationtype::name":"test",
  "tcomp::configurationtype::type":"checkpoint"
}
----


