== Component Server API
:page-talend_swaggerui:

++++
<script>
(window.talend = (window.talend || {})).swaggerUi = {"components":{"schemas":{"org_talend_sdk_component_runtime_server_vault_proxy_endpoint_proxy_LocalEnvironmentResource_Environment":{"properties":{"proxiedApiVersion":{"type":"integer"},"commit":{"type":"string"},"time":{"type":"string"},"version":{"type":"string"},"latestApiVersion":{"type":"integer"}},"type":"object"}}},"info":{"description":"Enables to decrypt credential through vault.","title":"Talend Component Server Vault Proxy","version":"1"},"openapi":"3.0.1","paths":{"/api/v1/action/execute":{"post":{"operationId":"execute","parameters":[{"in":"query","name":"family","schema":{"type":"string"},"style":"form"},{"in":"query","name":"type","schema":{"type":"string"},"style":"form"},{"in":"query","name":"action","schema":{"type":"string"},"style":"form"},{"in":"query","name":"lang","schema":{"type":"string"},"style":"form"}],"requestBody":{"content":{"application/json":{"schema":{"items":{},"type":"object"}}},"required":true},"responses":{"200":{"content":{"application/json":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}}},"description":"default response"},"default":{"content":{"application/json":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}}},"description":"default response"}}}},"/api/v1/action/index":{"get":{"operationId":"getIndex","parameters":[],"responses":{"200":{"content":{"application/json":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}}},"description":"default response"},"default":{"content":{"application/json":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}}},"description":"default response"}}}},"/api/v1/component/index":{"get":{"operationId":"getIndex_1","parameters":[],"responses":{"200":{"content":{"application/json":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}}},"description":"default response"},"default":{"content":{"application/json":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}}},"description":"default response"}}}},"/api/v1/component/icon/family/{id}":{"get":{"operationId":"familyIcon","parameters":[],"responses":{"200":{"content":{"application/json":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}},"application/octet-stream":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}},"image/svg+xml":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}}},"description":"default response"},"default":{"content":{"application/json":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}},"application/octet-stream":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}},"image/svg+xml":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}}},"description":"default response"}}}},"/api/v1/component/migrate/{id}/{configurationVersion}":{"post":{"operationId":"migrateComponent","parameters":[{"in":"path","name":"id","required":true,"schema":{"type":"string"},"style":"simple"},{"in":"path","name":"configurationVersion","required":true,"schema":{"type":"integer"},"style":"simple"}],"requestBody":{"content":{"application/json":{"schema":{"items":{},"type":"object"}}},"required":true},"responses":{"200":{"content":{"application/json":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}}},"description":"default response"},"default":{"content":{"application/json":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}}},"description":"default response"}}}},"/api/v1/component/details":{"get":{"operationId":"getDetail","parameters":[],"responses":{"200":{"content":{"application/json":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}}},"description":"default response"},"default":{"content":{"application/json":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}}},"description":"default response"}}}},"/api/v1/component/dependencies":{"get":{"operationId":"getDependencies","parameters":[],"responses":{"200":{"content":{"application/json":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}}},"description":"default response"},"default":{"content":{"application/json":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}}},"description":"default response"}}}},"/api/v1/component/dependency/{id}":{"get":{"operationId":"getDependency","parameters":[],"responses":{"200":{"content":{"application/octet-stream":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}}},"description":"default response"},"default":{"content":{"application/octet-stream":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}}},"description":"default response"}}}},"/api/v1/component/icon/{id}":{"get":{"operationId":"icon","parameters":[],"responses":{"200":{"content":{"application/json":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}},"application/octet-stream":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}},"image/svg+xml":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}}},"description":"default response"},"default":{"content":{"application/json":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}},"application/octet-stream":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}},"image/svg+xml":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}}},"description":"default response"}}}},"/api/v1/documentation/component/{id}":{"get":{"operationId":"getDocumentation","parameters":[],"responses":{"200":{"content":{"application/json":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}}},"description":"default response"},"default":{"content":{"application/json":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}}},"description":"default response"}}}},"/api/v1/environment":{"get":{"operationId":"get","parameters":[],"responses":{"200":{"content":{"*/*":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}}},"description":"default response"},"default":{"content":{"*/*":{"schema":{"items":{"nullable":true,"properties":{},"type":"object"},"type":"array"}}},"description":"default response"}}}},"/api/v1/proxy/environment":{"get":{"operationId":"get_1","parameters":[],"responses":{"200":{"content":{"application/json":{"schema":{"$ref":"#/components/schemas/org_talend_sdk_component_runtime_server_vault_proxy_endpoint_proxy_LocalEnvironmentResource_Environment","type":"object"}}},"description":"default response"},"default":{"content":{"application/json":{"schema":{"$ref":"#/components/schemas/org_talend_sdk_component_runtime_server_vault_proxy_endpoint_proxy_LocalEnvironmentResource_Environment","type":"object"}}},"description":"default response"}}}}},"servers":[{"url":"https://starter-toolkit.talend.io/api/demo/1.48.0"}]};</script>
<div id="swagger-ui"></div>
++++
