

= @DefaultValue

Provide a default value the UI can use - only for primitive fields.

- API: `@org.talend.sdk.component.api.configuration.ui.DefaultValue`

== Snippets

[source,js]
----
{
  "ui::defaultvalue::value":"test"
}
----


= @Hidden

Mark an @Option as being hidden.

- API: `@org.talend.sdk.component.api.configuration.ui.Hidden`

== Snippets

[source,js]
----
{
  "ui::hidden":"true"
}
----


= @OptionsOrder

Allows to sort a class properties.

- API: `@org.talend.sdk.component.api.configuration.ui.OptionsOrder`

== Snippets

[source,js]
----
{
  "ui::optionsorder::value":"value1,value2"
}
----


= @AutoLayout

Request the rendered to do what it thinks is best.

- API: `@org.talend.sdk.component.api.configuration.ui.layout.AutoLayout`

== Snippets

[source,js]
----
{
  "ui::autolayout":"true"
}
----


= @GridLayout

Advanced layout to place properties by row, this is exclusive with `@OptionsOrder`.

NOTE: the logic to handle forms (gridlayout names) is to use the only layout if there is only one defined, else to check if there are `Main` and `Advanced` and if at least `Main` exists, use them, else use all available layouts.

- API: `@org.talend.sdk.component.api.configuration.ui.layout.GridLayout`

== Snippets

[source,js]
----
{
  "ui::gridlayout::value1::value":"first|second,third",
  "ui::gridlayout::value2::value":"first|second,third"
}
----


= @GridLayouts

Allow to configure multiple grid layouts on the same class, qualified with a classifier (name)

- API: `@org.talend.sdk.component.api.configuration.ui.layout.GridLayouts`

== Snippets

[source,js]
----
{
  "ui::gridlayout::Advanced::value":"another",
  "ui::gridlayout::Main::value":"first|second,third"
}
----


= @HorizontalLayout

Put on a configuration class it notifies the UI an horizontal layout is preferred.

- API: `@org.talend.sdk.component.api.configuration.ui.layout.HorizontalLayout`

== Snippets

[source,js]
----
{
  "ui::horizontallayout":"true"
}
----


= @VerticalLayout

Put on a configuration class it notifies the UI a vertical layout is preferred.

- API: `@org.talend.sdk.component.api.configuration.ui.layout.VerticalLayout`

== Snippets

[source,js]
----
{
  "ui::verticallayout":"true"
}
----


= @BasedOnSchema

Mark a table column filled by component's schema auto. Only for studio.

- API: `@org.talend.sdk.component.api.configuration.ui.widget.BasedOnSchema`

== Snippets

[source,js]
----
{
  "ui::basedonschema":"true"
}
----


= @Code

Mark a field as being represented by some code widget (vs textarea for instance).

- API: `@org.talend.sdk.component.api.configuration.ui.widget.Code`

== Snippets

[source,js]
----
{
  "ui::code::value":"test"
}
----


= @Credential

Mark a field as being a credential. It is typically used to hide the value in the UI.

- API: `@org.talend.sdk.component.api.configuration.ui.widget.Credential`

== Snippets

[source,js]
----
{
  "ui::credential":"true"
}
----


= @DateTime

Mark a field as being a date. It supports and is *implicit* - which means you don't need to put that annotation on the option - for `java.time.ZonedDateTime`, `java.time.LocalDate` and `java.time.LocalDateTime` and is unspecified for other types.

- API: `@org.talend.sdk.component.api.configuration.ui.widget.DateTime`

== Snippets

[source,js]
----
{
  "ui::datetime":"time",
  "ui::datetime::useSeconds":"false"
}
----

[source,js]
----
{
  "ui::datetime":"date",
  "ui::datetime::dateFormat":"test"
}
----

[source,js]
----
{
  "ui::datetime":"datetime",
  "ui::datetime::dateFormat":"test",
  "ui::datetime::useSeconds":"false",
  "ui::datetime::useUTC":"false"
}
----

[source,js]
----
{
  "ui::datetime":"zoneddatetime",
  "ui::datetime::dateFormat":"test",
  "ui::datetime::useSeconds":"false",
  "ui::datetime::useUTC":"false"
}
----


= @ModuleList

Mark a string field as being represented by selected module list widget, only for studio

- API: `@org.talend.sdk.component.api.configuration.ui.widget.ModuleList`

== Snippets

[source,js]
----
{
  "ui::modulelist":"true"
}
----


= @Path

Mark a option as being represented by file or directory widget. Only for studio.

- API: `@org.talend.sdk.component.api.configuration.ui.widget.Path`

== Snippets

[source,js]
----
{
  "ui::path::value":"null"
}
----


= @ReadOnly

Mark a option as being read-only widget. User cannot modify widget.

- API: `@org.talend.sdk.component.api.configuration.ui.widget.ReadOnly`

== Snippets

[source,js]
----
{
  "ui::readonly":"true"
}
----


= @Structure

Mark a List<String> or List<Object> field as being represented as the component data selector.

- API: `@org.talend.sdk.component.api.configuration.ui.widget.Structure`

== Snippets

[source,js]
----
{
  "ui::structure::discoverSchema":"test",
  "ui::structure::type":"IN",
  "ui::structure::value":"test"
}
----


= @TextArea

Mark a field as being represented by a textarea(multiline text input).

- API: `@org.talend.sdk.component.api.configuration.ui.widget.TextArea`

== Snippets

[source,js]
----
{
  "ui::textarea":"true"
}
----


