= Component Server API
:page-talend_swaggerui:

++++
<script>
(window.talend = (window.talend || {})).swaggerUi = {"info":{"description":"Enables to decrypt credential through vault.","title":"Talend Component Server Vault Proxy","version":"1"},"openapi":"3.0.1","paths":{"/api/v1/component/migrate/{id}/{configurationVersion}":{"post":{"operationId":"migrateComponent","parameters":[{"in":"path","name":"id","required":true,"schema":{"type":"string"},"style":"simple"},{"in":"path","name":"configurationVersion","required":true,"schema":{"type":"integer"},"style":"simple"}],"requestBody":{"content":{"application/json":{"schema":{"items":{},"type":"object"}}},"required":true},"responses":{"200":{"content":{"application/json":{"schema":{"items":{"nullable":true,"type":"object"},"type":"array"}}},"description":"default response"},"default":{"content":{"application/json":{"schema":{"items":{"nullable":true,"type":"object"},"type":"array"}}},"description":"default response"}}}},"/api/v1/component/icon/family/{id}":{"get":{"operationId":"familyIcon","parameters":[],"responses":{"200":{"content":{"application/json":{"schema":{"items":{"nullable":true,"type":"object"},"type":"array"}},"application/octet-stream":{"schema":{"items":{"nullable":true,"type":"object"},"type":"array"}}},"description":"default response"},"default":{"content":{"application/json":{"schema":{"items":{"nullable":true,"type":"object"},"type":"array"}},"application/octet-stream":{"schema":{"items":{"nullable":true,"type":"object"},"type":"array"}}},"description":"default response"}}}},"/api/v1/component/index":{"get":{"operationId":"getIndex","parameters":[],"responses":{"200":{"content":{"application/json":{"schema":{"items":{"nullable":true,"type":"object"},"type":"array"}}},"description":"default response"},"default":{"content":{"application/json":{"schema":{"items":{"nullable":true,"type":"object"},"type":"array"}}},"description":"default response"}}}},"/api/v1/component/details":{"get":{"operationId":"getDetail","parameters":[],"responses":{"200":{"content":{"application/json":{"schema":{"items":{"nullable":true,"type":"object"},"type":"array"}}},"description":"default response"},"default":{"content":{"application/json":{"schema":{"items":{"nullable":true,"type":"object"},"type":"array"}}},"description":"default response"}}}},"/api/v1/component/dependencies":{"get":{"operationId":"getDependencies","parameters":[],"responses":{"200":{"content":{"application/json":{"schema":{"items":{"nullable":true,"type":"object"},"type":"array"}}},"description":"default response"},"default":{"content":{"application/json":{"schema":{"items":{"nullable":true,"type":"object"},"type":"array"}}},"description":"default response"}}}},"/api/v1/component/dependency/{id}":{"get":{"operationId":"getDependency","parameters":[],"responses":{"200":{"content":{"application/octet-stream":{"schema":{"items":{"nullable":true,"type":"object"},"type":"array"}}},"description":"default response"},"default":{"content":{"application/octet-stream":{"schema":{"items":{"nullable":true,"type":"object"},"type":"array"}}},"description":"default response"}}}},"/api/v1/component/icon/{id}":{"get":{"operationId":"icon","parameters":[],"responses":{"200":{"content":{"application/json":{"schema":{"items":{"nullable":true,"type":"object"},"type":"array"}},"application/octet-stream":{"schema":{"items":{"nullable":true,"type":"object"},"type":"array"}}},"description":"default response"},"default":{"content":{"application/json":{"schema":{"items":{"nullable":true,"type":"object"},"type":"array"}},"application/octet-stream":{"schema":{"items":{"nullable":true,"type":"object"},"type":"array"}}},"description":"default response"}}}}},"servers":[{"url":"https://tacokitexample.000webhostapp.com"}]};</script>
<div id="swagger-ui"></div>
++++
