

= Dynamic Values

Mark a method as being useful to fill potential values of a string option for a property denoted by its value. You can link a field as being completable using @Proposable(value). The resolution of the completion action is then done through the component family and value of the action. The callback doesn't take any parameter.

- Type: `dynamic_values`
- API: `@org.talend.sdk.component.api.service.completion.DynamicValues`
- Returned type: `org.talend.sdk.component.api.service.completion.Values`
- Sample:

[source,js]
----
{
  "items":[
    {
      "id":"value",
      "label":"label"
    }
  ]
}
----


= Healthcheck

This class marks an action doing a connection test

- Type: `healthcheck`
- API: `@org.talend.sdk.component.api.service.healthcheck.HealthCheck`
- Returned type: `org.talend.sdk.component.api.service.healthcheck.HealthCheckStatus`
- Sample:

[source,js]
----
{
  "comment":"Something went wrong",
  "status":"KO"
}
----


= Schema

Mark an action as returning a discovered schema. Its parameter MUST be the type decorated with `@Structure`.

- Type: `schema`
- API: `@org.talend.sdk.component.api.service.schema.DiscoverSchema`
- Returned type: `org.talend.sdk.component.api.service.schema.Schema`
- Sample:

[source,js]
----
{
  "entries":[
    {
      "name":"column1",
      "type":"STRING"
    }
  ]
}
----


= Suggestions

Mark a method as being useful to fill potential values of a string option. You can link a field as being completable using @Suggestable(value). The resolution of the completion action is then done when the user requests it (generally by clicking on a button or entering the field depending the environment).

- Type: `suggestions`
- API: `@org.talend.sdk.component.api.service.completion.Suggestions`
- Returned type: `org.talend.sdk.component.api.service.completion.SuggestionValues`
- Sample:

[source,js]
----
{
  "cacheable":false,
  "items":[
    {
      "id":"value",
      "label":"label"
    }
  ]
}
----


= User

-

- Type: `user`
- API: `@org.talend.sdk.component.api.service.Action`


= Validation

Mark a method as being used to validate a configuration. IMPORTANT: this is a server validation so only use it if you can't use other client side validation to implement it.

- Type: `validation`
- API: `@org.talend.sdk.component.api.service.asyncvalidation.AsyncValidation`
- Returned type: `org.talend.sdk.component.api.service.asyncvalidation.ValidationResult`
- Sample:

[source,js]
----
{
  "comment":"Something went wrong",
  "status":"KO"
}
----


