= Component Server API
:page-talend_swaggerui:

++++
<script>
(window.talend = (window.talend || {})).swaggerUi = {
  "openapi":"3.0.1",
  "servers": [{ url: "talend-component-kit-demo-server-talend-component-kit.193b.starter-ca-central-1.openshiftapps.com" }],
  "paths":{
    "/api/v1/action/index":{
      "get":{
        "deprecated":false,
        "description":"This endpoint returns the list of available actions for a certain family and potentially filters the output limiting it to some families and types of actions.",
        "operationId":"getIndex",
        "parameters":[
          {
            "allowEmptyValue":false,
            "allowReserved":false,
            "description":"the types of actions",
            "in":"query",
            "name":"type",
            "required":false,
            "schema":{
              "items":{

              },
              "properties":{

              }
            }
          },
          {
            "allowEmptyValue":false,
            "allowReserved":false,
            "description":"the families",
            "in":"query",
            "name":"family",
            "required":false,
            "schema":{
              "items":{

              },
              "properties":{

              }
            }
          },
          {
            "allowEmptyValue":false,
            "allowReserved":false,
            "description":"the language to use",
            "in":"query",
            "name":"language",
            "required":false,
            "schema":{
              "type":"string"
            }
          }
        ],
        "responses":{
          "200":{
            "content":{
              "application/json":{

              }
            },
            "description":"The action index."
          }
        },
        "tags":[
          "Action"
        ]
      }
    },
    "/api/v1/action/execute":{
      "post":{
        "deprecated":false,
        "description":"This endpoint will execute any UI action and serialize the response as a JSON (pojo model). It takes as input the family, type and name of the related action to identify it and its configuration as a flat key value set using the same kind of mapping than for components (option path as key).",
        "operationId":"execute",
        "parameters":[
          {
            "allowEmptyValue":false,
            "allowReserved":false,
            "description":"the component family",
            "in":"query",
            "name":"family",
            "required":true,
            "schema":{
              "type":"string"
            }
          },
          {
            "allowEmptyValue":false,
            "allowReserved":false,
            "description":"the type of action",
            "in":"query",
            "name":"type",
            "required":true,
            "schema":{
              "type":"string"
            }
          },
          {
            "allowEmptyValue":false,
            "allowReserved":false,
            "description":"the action name",
            "in":"query",
            "name":"action",
            "required":true,
            "schema":{
              "type":"string"
            }
          },
          {
            "allowEmptyValue":false,
            "allowReserved":false,
            "description":"the requested language (as in a Locale) if supported by the action",
            "in":"query",
            "name":"language",
            "required":false,
            "schema":{
              "type":"string"
            }
          }
        ],
        "requestBody":{
          "content":{
            "application/json":{
              "schema":{
                "type":"object"
              }
            }
          },
          "description":"the action parameters as a flat map of strings",
          "required":true
        },
        "responses":{
          "200":{
            "content":{
              "application/json":{

              }
            },
            "description":"The action payload serialized in JSON."
          },
          "520":{
            "content":{
              "application/json":{

              }
            },
            "description":"If the action execution failed, payload will be an ErrorPayload with the code ACTION_ERROR."
          },
          "400":{
            "content":{
              "application/json":{

              }
            },
            "description":"If the action is not set, payload will be an ErrorPayload with the code ACTION_MISSING."
          },
          "404":{
            "content":{
              "application/json":{

              }
            },
            "description":"If the action can't be found, payload will be an ErrorPayload with the code ACTION_MISSING."
          }
        },
        "tags":[
          "Action"
        ]
      }
    },
    "/api/v1/component/migrate/{id}/{configurationVersion}":{
      "post":{
        "deprecated":false,
        "description":"Allows to migrate a component configuration without calling any component execution.",
        "operationId":"migrate",
        "parameters":[
          {
            "allowEmptyValue":false,
            "allowReserved":false,
            "description":"the component identifier",
            "in":"path",
            "name":"id",
            "required":false,
            "schema":{
              "type":"string"
            }
          },
          {
            "allowEmptyValue":false,
            "allowReserved":false,
            "description":"the configuration version you send",
            "in":"path",
            "name":"configurationVersion",
            "required":false,
            "schema":{
              "type":"integer"
            }
          }
        ],
        "requestBody":{
          "content":{
            "application/json":{
              "schema":{
                "type":"object"
              }
            }
          },
          "description":"the actual configuration in key/value form.",
          "required":true
        },
        "responses":{
          "200":{
            "content":{
              "application/json":{

              }
            },
            "description":"the new configuration for that component (or the same if no migration was needed)."
          },
          "404":{
            "content":{
              "application/json":{

              }
            },
            "description":"The component is not found"
          }
        },
        "tags":[
          "Component"
        ]
      }
    },
    "/api/v1/component/icon/family/{id}":{
      "get":{
        "deprecated":false,
        "description":"Returns the icon for a family.",
        "operationId":"familyIcon",
        "parameters":[
          {
            "allowEmptyValue":false,
            "allowReserved":false,
            "description":"the family identifier",
            "in":"path",
            "name":"id",
            "required":false,
            "schema":{
              "type":"string"
            }
          }
        ],
        "responses":{
          "200":{
            "content":{
              "application/octet-stream":{

              }
            },
            "description":"Returns a particular family icon in raw bytes."
          },
          "404":{
            "content":{
              "application/json":{

              }
            },
            "description":"The family or icon is not found"
          }
        },
        "tags":[
          "Component"
        ]
      }
    },
    "/api/v1/component/index":{
      "get":{
        "deprecated":false,
        "description":"Returns the list of available components.",
        "operationId":"getIndex",
        "parameters":[
          {
            "allowEmptyValue":false,
            "allowReserved":false,
            "description":"the language for display names.",
            "in":"query",
            "name":"language",
            "required":false,
            "schema":{
              "type":"string"
            }
          },
          {
            "allowEmptyValue":false,
            "allowReserved":false,
            "description":"should the icon binary format be included in the payload.",
            "in":"query",
            "name":"includeIconContent",
            "required":false,
            "schema":{
              "type":"string"
            }
          }
        ],
        "responses":{
          "200":{
            "content":{
              "application/octet-stream":{

              }
            },
            "description":"The index of available components."
          }
        },
        "tags":[
          "Component"
        ]
      }
    },
    "/api/v1/component/details":{
      "get":{
        "deprecated":false,
        "description":"Returns the set of metadata about a few components identified by their 'id'.",
        "operationId":"getDetail",
        "parameters":[
          {
            "allowEmptyValue":false,
            "allowReserved":false,
            "description":"the language for display names.",
            "in":"query",
            "name":"language",
            "required":false,
            "schema":{
              "type":"string"
            }
          },
          {
            "allowEmptyValue":false,
            "allowReserved":false,
            "description":"the component identifiers to request, comma separated.",
            "in":"query",
            "name":"identifiers",
            "required":false,
            "schema":{
              "items":{

              },
              "properties":{

              }
            }
          }
        ],
        "responses":{
          "200":{
            "content":{
              "application/json":{

              }
            },
            "description":"the list of details for the requested components."
          },
          "400":{
            "content":{
              "application/json":{

              }
            },
            "description":"Some identifiers were not valid."
          }
        },
        "tags":[
          "Component"
        ]
      }
    },
    "/api/v1/component/dependencies":{
      "get":{
        "deprecated":false,
        "description":"Returns a list of dependencies for the given components. IMPORTANT: don't forget to add the component itself since it will not be part of the dependencies.Then you can use /dependency/{id} to download the binary.",
        "operationId":"getDependencies",
        "parameters":[
          {
            "allowEmptyValue":false,
            "allowReserved":false,
            "description":"the list of component identifiers to find the dependencies for.",
            "in":"query",
            "name":"identifier",
            "required":false,
            "schema":{
              "items":{

              },
              "properties":{

              }
            }
          }
        ],
        "responses":{
          "200":{
            "content":{
              "application/json":{

              }
            },
            "description":"The list of dependencies per component"
          }
        },
        "tags":[
          "Component"
        ]
      }
    },
    "/api/v1/component/dependency/{id}":{
      "get":{
        "deprecated":false,
        "description":"Return a binary of the dependency represented by `id`. It can be maven coordinates for dependencies or a component id.",
        "operationId":"getDependency",
        "parameters":[
          {
            "allowEmptyValue":false,
            "allowReserved":false,
            "description":"the dependency binary (jar).",
            "in":"path",
            "name":"id",
            "required":false,
            "schema":{
              "type":"string"
            }
          }
        ],
        "responses":{
          "200":{
            "content":{
              "application/octet-stream":{

              }
            },
            "description":"The dependency binary (jar)."
          }
        },
        "tags":[
          "Component"
        ]
      }
    },
    "/api/v1/component/icon/{id}":{
      "get":{
        "deprecated":false,
        "description":"Returns a particular component icon in raw bytes.",
        "operationId":"icon",
        "parameters":[
          {
            "allowEmptyValue":false,
            "allowReserved":false,
            "description":"the component icon identifier",
            "in":"path",
            "name":"id",
            "required":false,
            "schema":{
              "type":"string"
            }
          }
        ],
        "responses":{
          "200":{
            "content":{
              "application/octet-stream":{

              }
            },
            "description":"The component icon in binary form."
          },
          "404":{
            "content":{
              "application/json":{

              }
            },
            "description":"The family or icon is not found"
          }
        },
        "tags":[
          "Component"
        ]
      }
    },
    "/api/v1/configurationtype/migrate/{id}/{configurationVersion}":{
      "post":{
        "deprecated":false,
        "description":"Allows to migrate a configuration without calling any component execution.",
        "operationId":"migrate",
        "parameters":[
          {
            "allowEmptyValue":false,
            "allowReserved":false,
            "description":"the configuration identifier",
            "in":"path",
            "name":"id",
            "required":false,
            "schema":{
              "type":"string"
            }
          },
          {
            "allowEmptyValue":false,
            "allowReserved":false,
            "description":"the configuration version you send",
            "in":"path",
            "name":"configurationVersion",
            "required":false,
            "schema":{
              "type":"integer"
            }
          }
        ],
        "requestBody":{
          "content":{
            "application/json":{
              "schema":{
                "type":"object"
              }
            }
          },
          "description":"the actual configuration in key/value form.",
          "required":true
        },
        "responses":{
          "200":{
            "content":{
              "application/json":{

              }
            },
            "description":"the new values for that configuration (or the same if no migration was needed)."
          },
          "404":{
            "content":{
              "application/json":{

              }
            },
            "description":"The configuration is not found"
          }
        },
        "tags":[
          "Configuration Type"
        ]
      }
    },
    "/api/v1/configurationtype/index":{
      "get":{
        "deprecated":false,
        "description":"Returns all available configuration type - storable models. Note that the lightPayload flag allows to load all of them at once when you eagerly need  to create a client model for all configurations.",
        "operationId":"getRepositoryModel",
        "parameters":[
          {
            "allowEmptyValue":false,
            "allowReserved":false,
            "description":"the language for display names.",
            "in":"query",
            "name":"language",
            "required":false,
            "schema":{
              "type":"string"
            }
          },
          {
            "allowEmptyValue":false,
            "allowReserved":false,
            "description":"should the payload skip the forms and actions associated to the configuration.",
            "in":"query",
            "name":"lightPayload",
            "required":false,
            "schema":{
              "type":"boolean"
            }
          }
        ],
        "responses":{
          "200":{
            "content":{
              "application/json":{

              }
            },
            "description":"the list of available and storable configurations (datastore, dataset, ...)."
          }
        },
        "tags":[
          "Configuration Type"
        ]
      }
    },
    "/api/v1/configurationtype/details":{
      "get":{
        "deprecated":false,
        "description":"Returns all available configuration type - storable models. Note that the lightPayload flag allows to load all of them at once when you eagerly need  to create a client model for all configurations.",
        "operationId":"getDetail",
        "parameters":[
          {
            "allowEmptyValue":false,
            "allowReserved":false,
            "description":"the language for display names.",
            "in":"query",
            "name":"language",
            "required":false,
            "schema":{
              "type":"string"
            }
          },
          {
            "allowEmptyValue":false,
            "allowReserved":false,
            "description":"the comma separated list of identifiers to request.",
            "in":"query",
            "name":"identifiers",
            "required":false,
            "schema":{
              "items":{

              },
              "properties":{

              }
            }
          }
        ],
        "responses":{
          "200":{
            "content":{
              "application/json":{

              }
            },
            "description":"the list of available and storable configurations (datastore, dataset, ...)."
          }
        },
        "tags":[
          "Configuration Type"
        ]
      }
    },
    "/api/v1/documentation/component/{id}":{
      "get":{
        "deprecated":false,
        "description":"Returns an asciidoctor version of the documentation for the component represented by its identifier `id`. Format can be either asciidoc or html - if not it will fallback on asciidoc - and if html is selected you get a partial document. IMPORTANT: it is recommended to use asciidoc format and handle the conversion on your side if you can, the html flavor handles a limited set of the asciidoc syntax only like plain arrays, paragraph and titles. The documentation will likely be the family documentation but you can use anchors to access a particular component (_componentname_inlowercase).",
        "operationId":"getDocumentation",
        "parameters":[
          {
            "allowEmptyValue":false,
            "allowReserved":false,
            "description":"the component identifier",
            "in":"path",
            "name":"id",
            "required":false,
            "schema":{
              "type":"string"
            }
          },
          {
            "allowEmptyValue":false,
            "allowReserved":false,
            "description":"the language for display names.",
            "in":"query",
            "name":"language",
            "required":false,
            "schema":{
              "type":"string"
            }
          },
          {
            "allowEmptyValue":false,
            "allowReserved":false,
            "description":"the expected format (asciidoc or html).",
            "in":"query",
            "name":"format",
            "required":false,
            "schema":{
              "type":"string"
            }
          }
        ],
        "responses":{
          "200":{
            "content":{
              "application/json":{

              }
            },
            "description":"the list of available and storable configurations (datastore, dataset, ...)."
          }
        },
        "tags":[
          "Documentation"
        ]
      }
    },
    "/api/v1/environment":{
      "get":{
        "deprecated":false,
        "description":"Returns the environment of this instance. Useful to check the version or configure a healthcheck for the server.",
        "operationId":"get",
        "parameters":[
        ],
        "responses":{
          "200":{
            "content":{
              "application/json":{

              }
            },
            "description":"Current environment representation."
          }
        },
        "tags":[
          "Environment"
        ]
      }
    }
  },
  "tags":[
    {
      "description":"Endpoints related to callbacks/triggers execution.",
      "name":"Action"
    },
    {
      "description":"Endpoints related to callbacks/triggers execution.",
      "name":"Action"
    },
    {
      "description":"Endpoints related to callbacks/triggers execution.",
      "name":"Action"
    },
    {
      "description":"Endpoints related to component metadata access.",
      "name":"Component"
    },
    {
      "description":"Endpoints related to component metadata access.",
      "name":"Component"
    },
    {
      "description":"Endpoints related to component metadata access.",
      "name":"Component"
    },
    {
      "description":"Endpoints related to component metadata access.",
      "name":"Component"
    },
    {
      "description":"Endpoints related to component metadata access.",
      "name":"Component"
    },
    {
      "description":"Endpoints related to component metadata access.",
      "name":"Component"
    },
    {
      "description":"Endpoints related to component metadata access.",
      "name":"Component"
    },
    {
      "description":"Endpoints related to component metadata access.",
      "name":"Component"
    },
    {
      "description":"Endpoints related to configuration types (reusable configuration) metadata access.",
      "name":"Configuration Type"
    },
    {
      "description":"Endpoints related to configuration types (reusable configuration) metadata access.",
      "name":"Configuration Type"
    },
    {
      "description":"Endpoints related to configuration types (reusable configuration) metadata access.",
      "name":"Configuration Type"
    },
    {
      "description":"Endpoints related to configuration types (reusable configuration) metadata access.",
      "name":"Configuration Type"
    },
    {
      "description":"Endpoint to retrieve embedded component documentation.",
      "name":"Documentation"
    },
    {
      "description":"Endpoint to retrieve embedded component documentation.",
      "name":"Documentation"
    },
    {
      "description":"Endpoint giving access to versions and last update timestamp of the server.",
      "name":"Environment"
    },
    {
      "description":"Endpoint giving access to versions and last update timestamp of the server.",
      "name":"Environment"
    }
  ]
};</script>
<div id="swagger-ui"></div>
++++
