

= @DefaultValue

Provide a default value the UI can use - only for primitive fields.

- API: `@org.talend.sdk.component.api.configuration.ui.DefaultValue`

Sample:

[source,js]
----
{
  "ui::defaultvalue::value":"test"
}
----


= @OptionsOrder

Allows to sort a class properties.

- API: `@org.talend.sdk.component.api.configuration.ui.OptionsOrder`

Sample:

[source,js]
----
{
  "ui::optionsorder::value":"value1,value2"
}
----


= @AutoLayout

Request the rendered to do what it thinks is best.

- API: `@org.talend.sdk.component.api.configuration.ui.layout.AutoLayout`

Sample:

[source,js]
----
{
  "ui::autolayout":"true"
}
----


= @GridLayout

Advanced layout to place properties by row, this is exclusive with `@OptionsOrder`.

- API: `@org.talend.sdk.component.api.configuration.ui.layout.GridLayout`

Sample:

[source,js]
----
{
  "ui::gridlayout::value1::value":"first|second,third",
  "ui::gridlayout::value2::value":"first|second,third"
}
----


= @GridLayouts

Allow to configure multiple grid layouts on the same class, qualified with a classifier (name)

- API: `@org.talend.sdk.component.api.configuration.ui.layout.GridLayouts`

Sample:

[source,js]
----
{
  "ui::gridlayout::Advanced::value":"another",
  "ui::gridlayout::Main::value":"first|second,third"
}
----


= @HorizontalLayout

Put on a configuration class it notifies the UI an horizontal layout is preferred.

- API: `@org.talend.sdk.component.api.configuration.ui.layout.HorizontalLayout`

Sample:

[source,js]
----
{
  "ui::horizontallayout":"true"
}
----


= @VerticalLayout

Put on a configuration class it notifies the UI a vertical layout is preferred.

- API: `@org.talend.sdk.component.api.configuration.ui.layout.VerticalLayout`

Sample:

[source,js]
----
{
  "ui::verticallayout":"true"
}
----


= @Code

Mark a field as being represented by some code widget (vs textarea for instance).

- API: `@org.talend.sdk.component.api.configuration.ui.widget.Code`

Sample:

[source,js]
----
{
  "ui::code::value":"test"
}
----


= @Credential

Mark a field as being a credential. It is typically used to hide the value in the UI.

- API: `@org.talend.sdk.component.api.configuration.ui.widget.Credential`

Sample:

[source,js]
----
{
  "ui::credential":"true"
}
----


= @Structure

Mark a List<String> or Map<String, String> field as being represented as the component data selector (field names generally or field names as key and type as value).

- API: `@org.talend.sdk.component.api.configuration.ui.widget.Structure`

Sample:

[source,js]
----
{
  "ui::structure::discoverSchema":"test",
  "ui::structure::type":"IN",
  "ui::structure::value":"test"
}
----


= @TextArea

Mark a field as being represented by a textarea(multiline text input).

- API: `@org.talend.sdk.component.api.configuration.ui.widget.TextArea`

Sample:

[source,js]
----
{
  "ui::textarea":"true"
}
----


