== Component Server API
:page-talend_swaggerui:

++++
<script>
(window.talend = (window.talend || {})).swaggerUi = {"components":{},"info":{"description":"UI related component server to provide metadata about component and callback for the forms.","title":"Talend Component Server","version":"1"},"openapi":"3.0.1","paths":{},"tags":[{"description":"Endpoints related to callbacks/triggers execution.","name":"Action"},{"description":"Enables to execute multiple requests at once.","name":"Bulk"},{"description":"Endpoints related to component metadata access.","name":"Component"},{"description":"Endpoints related to configuration types (reusable configuration) metadata access.","name":"Configuration Type"},{"description":"Endpoint to retrieve embedded component documentation.","name":"Documentation"},{"description":"Endpoint giving access to versions and last update timestamp of the server.","name":"Environment"},{"description":"Endpoints related to caches management.","name":"Cache"}],"servers":[{"url":"https://starter-toolkit.talend.io/api/demo/1.2611.0"}]};</script>
<div id="swagger-ui"></div>
++++
