= Talend Component Programming Model
Romain Manni-Bucau
:revnumber: {project_version}

== Fully declarative

* annotation based
** to find the components
** to find the callbacks
** to match parameters (for extensibility)


== PartitionMapper

[source,java]
----
@PartitionMapper(component = "sample", name = "reader_mapper") <1>
public class PersonMapper implements Serializable {
    @Assessor <2>
    public long globalSize() {
        return ...;
    }

    @Split <3>
    public List<PersonMapper split(@PartitionSize long sizePerMapper) {
        return ...;
    }

    @Emitter <4>
    public PersonReader createReader() {
        return ...;
    }
}
----

<1> mark this component as a mapper
<2> mark this method as the one estimating the whole dataset size
<3> mark this method as the one dividing (map in map/reduce) the work in N _workers_
<4> create an actual reader (input) for the current instance of mapper (with its configuration etc)

== Inputs

[source,java]
----
@Emitter(component = "sample", name = "reader") <1>
public class PersonReader implements Serializable {
    @Producer <2>
    public Person readNext() {
        return ...;
    }
}
----

<1> mark this component as a direct (no mapper) input
<2> mark this method as the one loading data one by one


== Processor

[source,java]
----
@Processor(component = "sample", name = "processor") <1>
public class PersonProcessor implements Serializable {
    @ElementListener <2>
    public Record onNext(Person incoming) {
        return ...;
    }

    @BeforeGroup <3>
    public void prepareBatch() {
        // ...
    }

    @AfterGroup <3>
    public void performBatch() {
        // ...
    }
}
----

<1> mark this component as a processor
<2> mark this method as the one receiving data and converting it to any other tip
<3> mark this method as called before/after a chunk processing (multiple records - runner dependent)

TIP: a processor returning `void` is an output

== Configuring a component

* The simplest for a component to be configured is to use its constructor
* Primitives and complex objects (including lists and maps) can be used

[source,java]
----
public class MyComponent implements Serializable {
    public MyComponent(@Option("location") String location,
                       @Option("security") SecurityConfiguration security) {
        // ...
    }
}
----

* A mapping is done from flat properties to that model

== Services


[source,java]
----
@Service <1>
public class PersonService {
    @Action("person::check_exists") <2>
    public boolean checkExists(Person incoming) {
        return ...;
    }
}
----

<1> mark this class as being a service
<2> mark this method as being some processing related to the component of the _current_ plugin

IMPORTANT: these services are intended to be used by a client, not internally by component _for now_.
NOTE: parameter injection follows component configuration logic.

== DataSets and DataStores

* The framework supports to decorate configurations with a particular annotations usable to identify a particular type if configuration
** `@DataSet("name")`
** `@DataStore("name")`

* The configuration is not duplicated and not propagated everywhere if not needed!

== Configuration and Lifecycle

* All components support `@PostConstruct` and `@PreDestroy` for global start/stop lifecycle management

[source,java]
----
public clas SomeComponent {
    // ...

    @PostConstruct
    public void initConnection() {
        // ...
    }

    @PreDestroy
    public void releaseConnection() {
        // ...
    }
}
----

== Thanks
