[versions]
# libraries
lombok = "1.18.36"
junit = "4.13.2"
opentest4j = "1.3.0"
# last one that uses java 17
javafx = "22.0.2"

# plugins
changelog = "2.2.1"
intelliJPlatform = "2.5.0"
kotlin = "2.1.20"

[libraries]
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }
openjfxBase = { group = "org.openjfx", name = "javafx-base", version.ref = "javafx" }
openjfxControls = { group = "org.openjfx", name = "javafx-controls", version.ref = "javafx" }
openjfxFxml = { group = "org.openjfx", name = "javafx-fxml", version.ref = "javafx" }
openjfxGraphics = { group = "org.openjfx", name = "javafx-graphics", version.ref = "javafx" }
openjfxMedia = { group = "org.openjfx", name = "javafx-media", version.ref = "javafx" }
openjfxSwing = { group = "org.openjfx", name = "javafx-swing", version.ref = "javafx" }
openjfxWeb = { group = "org.openjfx", name = "javafx-web", version.ref = "javafx" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }