= Talend Component REST API Documentation
:toc:
:numbered:
:icons: font
:hide-uri-scheme:
:imagesdir: images
:outdir: ../assets
:jbake-type: page
:jbake-tags: documentation
:jbake-status: published

== REST API

The REST API intends to expose over HTTP most of Talend Component features, it is a standalone Java HTTP server.

TIP: WebSocket protocol is activated for the endpoints as well, instead of `/api/v1` they uses the base `/websocket/v1`, see WebSocket part for more details.

Here is the API:

include::../../../../../component-server/target/jaxrs-analyzer/rest-resources.adoc[leveloffset=2]

IMPORTANT: to ensure the migration can be activated you need to set in the execution configuration you send to the server
the version it was created with (component version, it is in component detail endpoint) with the key `tcomp::component::version`.

=== WebSocket transport

You can connect on any endpoint replacing `/api` by `/websocket` and appending `/<http method>` for the URL and formatting the request as:

[source]
----
SEND
destination: <endpoint after v1>
<headers>

<payload>^@
----

For instance:

[source]
----
SEND
destination: /component/index
Accept: application/json

^@
----

The response is formatted as follow:

[source]
----
MESSAGE
status: <http status code>
<headers>

<payload>^@
----

TIP: if you have a doubt about the endpoint, they are all logged during startup and you can find them in the logs.

== Web forms and REST API

`component-form` library provides a way to build a component REST API facade compatible with react form library.

A trivial facade can be:

[source,java]
----
@Path("tcomp-facade")
@ApplicationScoped
public class ComponentFacade {

    @Inject
    private Client client;

    @Inject
    private UiSpecService uiSpecService;

    @Inject
    private ActionService actionService;

    @POST
    @Path("action")
    public UiActionResult action(@QueryParam("family") final String family, @QueryParam("type") final String type,
            @QueryParam("action") final String action, final Map<String, Object> params) {
        try {
            return actionService.map(type, client.action(family, type, action, params));
        } catch (final WebException exception) {
            final UiActionResult payload = actionService.map(exception);
            throw new WebApplicationException(Response.status(exception.getStatus()).entity(payload).build());
        }
    }

    @GET
    @Path("index")
    public ComponentIndices getIndex(@QueryParam("language") @DefaultValue("en") final String language) {
        final ComponentIndices index = client.index(language);
        // our mapping is a bit different so rewrite links
        index.getComponents().stream().flatMap(c -> c.getLinks().stream()).forEach(link -> link.setPath(
                link.getPath().replaceFirst("\\/component\\/", "\\/tcomp-facade\\/").replace("/details?identifiers=", "/detail/")));
        return index;
    }

    @GET
    @Path("detail/{id}")
    public UiSpecPayload getDetail(@QueryParam("language") @DefaultValue("en") final String language,
            @PathParam("id") final String id) {
        final List<ComponentDetail> details = client.details(language, id, new String[0]).getDetails();
        if (details.isEmpty()) {
            throw new WebApplicationException(Response.Status.BAD_REQUEST);
        }
        return uiSpecService.convert(details.iterator().next());
    }
}
----

NOTE: the `Client` can be created using `ClientFactory.createDefault(System.getProperty("app.components.base", "http://localhost:8080/api/v1"))`
and the service can be a simple `new UiSpecService()`.

All the conversion between component model (REST API) and uiSpec model is done through the `UiSpecService`. It is based on the object model
which will be mapped to a ui model. The advantage to have a flat model in the component REST API is to make these layers easy to customize.

You can completely control the available components, tune the rendering switching the `uiSchema` if desired or add/remove part of the form.
You can also add custom actions/buttons for specific needs of the application.

NOTE: the  `/migrate` endpoint has nothing special so was not shown in previous snippet but if you need it you must add it as well.

== Logging

The logging uses Log4j2, you can specify a custom configuration using the system property `-Dlog4j.configurationFile`
or adding a `log4j2.xml` file into the classpath.

Here are some common configurations:

- Console logging:

[source,xml]
----
<?xml version="1.0"?>
<Configuration status="INFO">
  <Appenders>
    <Console name="Console" target="SYSTEM_OUT">
      <PatternLayout pattern="[%d{HH:mm:ss.SSS}][%highlight{%-5level}][%15.15t][%30.30logger] %msg%n"/>
    </Console>
  </Appenders>
  <Loggers>
    <Root level="INFO">
      <AppenderRef ref="Console"/>
    </Root>
  </Loggers>
</Configuration>
----

This outputs messages looking like:

[source]
----
[16:59:58.198][INFO ][           main][oyote.http11.Http11NioProtocol] Initializing ProtocolHandler ["http-nio-34763"]
----

- JSON logging:

[source,xml]
----
<?xml version="1.0"?>
<Configuration status="INFO">
  <Properties>
    <!-- DO NOT PUT logSource there, it is useless and slow -->
    <Property name="jsonLayout">{"severity":"%level","logMessage":"%encode{%message}{JSON}","logTimestamp":"%d{ISO8601}{UTC}","eventUUID":"%uuid{RANDOM}","@version":"1","logger.name":"%encode{%logger}{JSON}","host.name":"${hostName}","threadName":"%encode{%thread}{JSON}","stackTrace":"%encode{%xThrowable{full}}{JSON}"}%n</Property>
  </Properties>
  <Appenders>
    <Console name="Console" target="SYSTEM_OUT">
      <PatternLayout pattern="${jsonLayout}"/>
    </Console>
  </Appenders>
  <Loggers>
    <Root level="INFO">
      <AppenderRef ref="Console"/>
    </Root>
  </Loggers>
</Configuration>
----

Output messages look like:

[source]
----
{"severity":"INFO","logMessage":"Initializing ProtocolHandler [\"http-nio-46421\"]","logTimestamp":"2017-11-20T16:04:01,763","eventUUID":"8b998e17-7045-461c-8acb-c43f21d995ff","@version":"1","logger.name":"org.apache.coyote.http11.Http11NioProtocol","host.name":"TLND-RMANNIBUCAU","threadName":"main","stackTrace":""}
----

- Rolling file appender

[source]
----
<?xml version="1.0"?>
<Configuration status="INFO">
  <Appenders>
    <RollingRandomAccessFile name="File" fileName="${LOG_PATH}/application.log" filePattern="${LOG_PATH}/application-%d{yyyy-MM-dd}.log">
      <PatternLayout pattern="[%d{HH:mm:ss.SSS}][%highlight{%-5level}][%15.15t][%30.30logger] %msg%n"/>
      <Policies>
        <SizeBasedTriggeringPolicy size="100 MB" />
        <TimeBasedTriggeringPolicy interval="1" modulate="true"/>
      </Policies>
    </RollingRandomAccessFile>
  </Appenders>
  <Loggers>
    <Root level="INFO">
      <AppenderRef ref="File"/>
    </Root>
  </Loggers>
</Configuration>
----

More details are available on link:https://logging.apache.org/log4j/2.x/manual/appenders.html#RollingFileAppender[RollingFileAppender] documentation.


TIP: of course you can compose previous layout (message format) and appenders (where logs are written).
