= Talend Component Documentation Testing
:toc:
:numbered:
:icons: font
:hide-uri-scheme:
:imagesdir: images
:outdir: ../assets
:jbake-type: page
:jbake-tags: documentation, testing
:jbake-status: published

[[documentation-testing-start]]
== Best practises

NOTE: this part is mainly around tools usable with JUnit. You can use most of these techniques with TestNG
as well, check out the documentation if you need to use TestNG.

=== Parameterized tests

This is a great solution to repeat the same test multiple times. Overall idea
is to define a test scenario (`I test function F`) and to make the input/output data
dynamic.

Here is an example. Let's assume we have this test which validates the connection URI using `ConnectionService`:

[source,java]
----
public class MyConnectionURITest {
    @Test
    public void checkMySQL() {
        assertTrue(new ConnectionService().isValid("jdbc:mysql://localhost:3306/mysql"));
    }

    @Test
    public void checkOracle() {
        assertTrue(new ConnectionService().isValid("jdbc:oracle:thin:@//myhost:1521/oracle"));
    }
}
----

We clearly identify the test method is always the same except the value. It can therefore be rewritter
using JUnit `Parameterized` runner like that:

[source,java]
----
@RunWith(Parameterized.class) <1>
public class MyConnectionURITest {

    @Parameterized.Parameters(name = "{0}") <2>
    public static Iterable<String> uris() { <3>
        return asList(
            "jdbc:mysql://localhost:3306/mysql",
            "jdbc:oracle:thin:@//myhost:1521/oracle");
    }

    @Parameterized.Parameter <4>
    public String uri;

    @Test
    public void isValid() { <5>
        assertNotNull(uri);
    }
}
----

<1> `Parameterized` is the runner understanding `@Parameters` and how to use it. Note that you can generate random data here if desired.
<2> by default the name of the executed test is the index of the data, here we customize it using the first parameter `toString()` value to have something more readable
<3> the `@Parameters` method `MUST` be static and return an array or iterable of the data used by the tests
<4> you can then inject the current data using `@Parameter` annotation, it can take a parameter if you use an array of array instead of an iterable of object in `@Parameterized` and you can select which item you want injected this way
<5> the `@Test` method will be executed using the contextual data, in this sample we'll get executed twice with the 2 specified urls

TIP: you don't have to define a single `@Test` method, if you define multiple, each of them will be executed with all the data (ie if we add a test in previous example you will get 4 tests execution - 2 per data, ie 2x2)

== component-runtime-testing

=== component-runtime-junit

`component-runtime-junit` is a small test library allowing you to validate simple logic based on Talend Component tooling.

To import it add to your project the following dependency:


[source,xml]
----
<dependency>
  <groupId>org.talend.sdk.component</groupId>
  <artifactId>component-runtime-junit</artifactId>
  <version>${talend-component.version}</version>
  <scope>test</scope>
</dependency>
----


Then you can define a standard JUnit test and use the `SimpleComponentRule` rule:

[source,java]
----
public class MyComponentTest {

    @Rule <1>
    public final SimpleComponentRule components = new SimpleComponentRule("org.talend.sdk.component.mycomponent.");

    @Test
    public void produce() {
        ExecutionChainBuilder.start() <2>
                .fromInput("yourcomponentfamily", "yourcomponent", createComponentConfig())
                .toProcessor("test", "collector", emptyMap())
                .create(components.asManager(), p -> null, Assert::assertNotNull, (data, exception) -> {
                    fail(exception.getMessage());
                    return null;
                }).get().execute();

        final List<MyRecord> records = components.getCollectedData(MyRecord.class); <3>
        doAssertRecords(records); // depending your test
    }
}
----

<1> the rule will create a component manager and provide two mock components: an emitter and a collector. Don't forget to set the root package of your component to enable it.
<2> you define any chain you want to test, it generally uses the mock as source or collector
<3> you validate your component behavior, for a source you can assert the right records were emitted in the mock collect

==== Mocking the output

Using the component "test"/"collector" as in previous sample stores all records emitted by the chain (typically your source)
in memory, you can then access them using `theSimpleComponentRule.getCollectoedRecord(type)`. Note that this method filters by type,
if you don't care of the type just use `Object.class`.

==== Mocking the input

The input mocking is symmetric to the output but here you provide the data you want to inject:

[source,java]
----
public class MyComponentTest {

    @Rule
    public final SimpleComponentRule components = new SimpleComponentRule("org.talend.sdk.component.mycomponent.");

    @Test
    public void produce() {
        components.setInputData(asList(createData(), createData(), createData())); <1>

        ExecutionChainBuilder.start() <2>
                .fromInput("test", "emitter", emptyMap())
                .toProcessor("yourcomponentfamily", "myoutput", createComponentConfig())
                .create(components.asManager(), p -> null, Assert::assertNotNull, (data, exception) -> {
                    fail(exception.getMessage());
                    return null;
                }).get().execute();

        assertMyOutputProcessedTheInputData();
    }
}
----

<1> using `setInputData` you prepare the execution(s) to have a fake input when using "test"/"emitter" component.

==== Creating runtime configuration from component configuration

The component configuration is a POJO (using `@Option` on fields) and the runtime configuration (`ExecutionChainBuilder`) uses
a `Map<String, String>`. To make the conversion easier, the JUnit integration provides a `SimpleFactory.configurationByExample` utility
to get this map instance from a configuration instance.

Example:

[source,java]
----
final MyComponentConfig componentConfig = new MyComponentConfig();
componentConfig.setUser("....");
// .. other inits

final Map<String, String> configuration = configurationByExample(componentConfig);
----

==== Testing a Mapper

The `SimpleComponentRule` also allows to test a mapper unitarly, you can get an instance from a configuration
and you can execute this instance to collect the output. Here is a snippet doing that:

[source,java]
----
public class MapperTest {

    @ClassRule
    public static final SimpleComponentRule COMPONENT_FACTORY = new SimpleComponentRule(
            "org.company.talend.component");

    @Test
    public void mapper() {
        final Mapper mapper = COMPONENT_FACTORY.createMapper(MyMapper.class, new Source.Config() {{
            values = asList("a", "b");
        }});
        assertEquals(asList("a", "b"), COMPONENT_FACTORY.collectAsList(String.class, mapper));
    }
}
----

==== Testing a Processor

As for the mapper a processor is testable unitarly. The case is a bit more complex since you can have multiple
inputs and outputs:

[source,java]
----
public class ProcessorTest {

    @ClassRule
    public static final SimpleComponentRule COMPONENT_FACTORY = new SimpleComponentRule(
            "org.company.talend.component");

    @Test
    public void processor() {
        final Processor processor = COMPONENT_FACTORY.createProcessor(Transform.class, null);
        final SimpleComponentRule.Outputs outputs = COMPONENT_FACTORY.collect(processor,
                new JoinInputFactory(new HashMap<String, Iterator<?>>() {{
                    put("__default__", asList(new Transform.Record("a"), new Transform.Record("bb")).iterator());
                    put("second", asList(new Transform.Record("1"), new Transform.Record("2")).iterator());
                }}));
        assertEquals(2, outputs.size());
        assertEquals(asList(2, 3), outputs.get(Integer.class, "size"));
        assertEquals(asList("a1", "bb2"), outputs.get(String.class, "value"));
    }
}
----

Here again the rule allows you to instantiate a `Processor` from your code
and then to `collect` the output from the inputs you pass in. There are two convenient implementation
of the input factory:

1. `MainInputFactory` for processors using only the default input.
2. `JoinInputfactory` for processors using multiple inputs. This one takes a map of iterators. The key is the branch name and the value the data used by the branch.

TIP: you can also implement your own input representation if needed implementing `org.talend.sdk.component.junit.ControllableInputFactory`.

=== component-runtime-testing-spark

The folowing artifact will allow you to test against a spark cluster:

[source,xml]
----
<dependency>
  <groupId>org.talend.sdk.component</groupId>
  <artifactId>component-runtime-testing-spark</artifactId>
  <version>${talend-component.version}</version>
  <scope>test</scope>
</dependency>
----

The usage relies on a JUnit `TestRule`. It is recommanded to use it as a `@ClassRule` to ensure
a single instance of a spark cluster is built but you can also use it as a simple `@Rule` which means
it will be created per method instead of per test class.

It takes as parameter the spark and scala version to use. It will then fork a master and N slaves.
Finally it will give you `submit*` method allowing you to send jobs either from the test classpath
or from a shade if you run it as an integration test.

Here is a sample:

[source,java]
----
public class SparkClusterRuleTest {

    @ClassRule
    public static final SparkClusterRule SPARK = new SparkClusterRule("2.10", "1.6.3", 1);

    @Test
    public void classpathSubmit() throws IOException {
        SPARK.submitClasspath(SubmittableMain.class, getMainArgs());

        // do wait the test passed
    }
}
----

TIP: this is working with `@Parameterized` so you can submit a bunch of jobs with different args and even combine it with beam `TestPipeline` if you make it `transient`!

==== How to know the job is done

In current state, `SparkClusterRule` doesn't allow to know a job execution is done - even if it exposes the webui url so
you can poll it to check. The best at the moment is to ensure the output of your job exists and contains the right value.

`awaitability` or equivalent library can help you to write such logic.

Here are the coordinates of the artifact:

[source,xml]
----
<dependency>
  <groupId>org.awaitility</groupId>
  <artifactId>awaitility</artifactId>
  <version>3.0.0</version>
  <scope>test</scope>
</dependency>
----

And here is how to wait a file exists and its content (for instance) is the expected one:

[source,java]
----
await()
    .atMost(5, MINUTES)
    .until(
        () -> out.exists() ? Files.readAllLines(out.toPath()).stream().collect(joining("\n")).trim() : null,
        equalTo("the expected content of the file"));
----

== Beam testing

If you want to ensure your component works in Beam the minimum to do is to try with the direct runner (if you don't want to use spark).

Check https://beam.apache.org/contribute/testing/ out for more details.

== Generating data?

Several data generator exists if you want to populate objects with a semantic a bit more evolved than a plain random string
like `commons-lang3`:

* https://github.com/Codearte/jfairy
* https://github.com/DiUS/java-faker
* https://github.com/andygibson/datafactory
* ...

A bit more advanced, these ones allow to bind directly generic data on a model - but data quality is not always there:

* https://github.com/devopsfolks/podam
* https://github.com/benas/random-beans
* ...

Note there are two main kind of implementations:

* the one using a _pattern_ and random generated data
* a set of precomputed data extrapolated to create new values

Check against your use case to know which one is the best.

NOTE: an interesting alternative to data generation is to import _real_ data and use Talend Studio to sanitize the data (remove sensitive information replacing them by generated data or anonymized data)
and just inject that file into the system.
