= Talend Component i18n Extension
:toc:
:numbered:
:icons: font
:hide-uri-scheme:
:imagesdir: images
:outdir: ../assets
:jbake-type: page
:jbake-tags: documentation, extension, i18n
:jbake-status: published

== Goal

The high level goal is to allow you to plug any resource bundle implementation on the JVM
and therefore plug the logic you want behind lines like:

[source,java]
----
ResourceBundle rb = ResourceBundle.getBundle("my.Bundle");
----

`ResourceBundle` is the standard API in Java for internationalization and is used by the component framework.
By default it supports two formats:

- properties where files are suffixed with `[_<locale>].properties`
- classes where the classes are loaded from the bundle name with the same kind of naming convention than the properties flavor

However both solutions imply to put the translations aside the code and to bundle it along side the sources.
In practise it is common to externalize the translations to let people interact with it more easily or even plug their own messages.

To solve that, the `i18n-loader` module plugs a global strategy which is tested before any default strategy.

== Installation

=== Java 8

On Java 8 you need to download the `i18n-loader.jar` and add it to your extension classloader. It is done
setting the system property `java.ext.dirs` on the JVM. Here are the detailled steps:

1. download `i18n-loader.jar` in a folder (we will use `/opt/exts/` in our examples)
2. set on your JVM the `java.ext.dirs` system property based on the default one (`$JRE_HOME/lib/ext`) and our custom `/opt/exts` directory:

[source]
----
// for linux when JAVA_HOME is a JRE
"-Djava.ext.dirs=$JAVA_HOME/lib/ext:/opt/exts"

// for linux when JAVA_HOME is a JDK
"-Djava.ext.dirs=$JAVA_HOME/jre/lib/ext:/opt/exts"

// for windows when JAVA_HOME is a JRE
-Djava.ext.dirs=%JAVA_HOME%/lib/ext;/opt/exts

// for windows when JAVA_HOME is a JDK
-Djava.ext.dirs=%JAVA_HOME%/jre/lib/ext;/opt/exts
----

== Usage

The extension itself doesn't provide any alternative implementation and just setting it up you will fallback
on the default JVM behavior.

However it provides API to register custom logic.

The entry point is the `ProviderLocator` which allows you to register a custom `ResourceBundleControlProvider`
and associate it with a `ClassLoader` used as identifier for an application. This means you can register
one provider per application if desired!

IMPORTANT: you don't need to register your `ResourceBundleControlProvider` through Java SPI mecanism (`META-INF/services`),
the extension only uses the `ProviderLocator` registry.

Then you need to register your own implementation using the register method of the locator. It will return you
a `Runnable` you have to call when you undeploy/shutdown your application to unregister your implementation.

[source,java]
----
final Runnable deregister = ProviderLocator.instance().register(myAppClassLoader, new MyCustomControlProvider());
// app life
deregister.run();
----

In a servlet context you can use a web listener:

[source,java]
----
@WebListener
public class MyI18nLifecycle implement ServletContextListener {
    private Runnable deregister;

    @Override
    public void contextInitialized(ServletContextEvent evt) {
        deregister = ProviderLocator.instance()
            .register(evt.getServletContext().getClassLoader(), new MyCustomControlProvider());
    }

    @Override
    public void contextDestroyed(ServletContextEvent evt) {
        deregister.run();
    }
}
----

IMPORTANT: if you use maven don't forget to use the scope `provided` for `i18n-loader` dependency.

To implement your custom control provider the library provides you some helper classes.

The main helpers are:

- `BaseProvider` which simplifies the control provider implementation, it provides a filter of supported bundles
and the bundle factory:

[source,java]
----
public class MyControlProvider extends BaseProvider {
    @Override
    protected boolean supports(final String baseName) {
        return baseName.startsWith("com.company.");
    }

    @Override
    protected ResourceBundle createBundle(final String baseName, final Locale locale) {
        return ...;
    }
}
----

Note that this base has also a shortcut in the provider locator for the registration allowing you
to use lambdas:

[source,java]
----
// newBundle is your custom bundle creation logic
ProviderLocator.instance()
  .register(loader, name -> name.startsWith("com.company"), (name, locale) -> newBundle(name, locale));
----

- `BaseControl` is an adapter of `java.util.ResourceBundle.Control`
- `BaseBundle` is an adapter of `java.util.ResourceBundle` allowing you to implement only a few methods:

[source,java]
----
public class MyBundle extends BaseBundle {
    @Override
    protected Set<String> doGetKeys() {
        return Collections.singleton("thekey");
    }

    @Override
    protected Object handleGetObject(final String key) {
        return "thekey".equals(key) ? "thevalue" : null;
    }
}
----

In practise you will pass it the bundle name and locale from a `BaseProvider` or equivalent
and load the keys with some custom logic.

- `MapBundle` is a custom resource bundle backed by a map, in practise you will likely pass a concurrent map
implementation to support live updates if needed from the outside of the bundle
