= Talend Component Studio Integration
:toc:
:numbered:
:icons: font
:hide-uri-scheme:
:imagesdir: images
:outdir: ../assets
:jbake-type: page
:jbake-tags: documentation, studio
:jbake-status: published

== Design

The studio integration relies on Component Server (see <<documentation-rest.adoc#, Web>> for more details).

When the plugin is deployed it starts a local server the Studio uses to gather data about the components.

== Installation

Copy `org.talend.sdk.component.studio-integration.jar` in the `$STUDIO_HOME/plugins` directory and restart the studio.

Also ensure the `component-server` dependencies  and `commons-cli` 1.4 are into the Studio maven repository. If you install any component,
ensure its dependencies are in the repository as well.

TIP: you can set in `$STUDIO_HOME/configuration/config.ini` the value `maven.repository` to `global` to reuse
your local maven repository.

== Configuration

The configuration goes into `$STUDIO_HOME/configuration/config.ini`.

|===
| Name | Description | Default
| component.java.options | JVM options to pass to the component server | -Xmx256m
| component.java.arguments | Component server additional options | -
| component.java.m2 | The maven repository the server uses to resolve components | default to global Studio configuration
| component.java.coordinates | A list of comma separated GAV (groupId:artifactId:version) of components to register | -
| component.java.registry | A properties file with values matching component GAV (groupId:artifactId:version) which are registered at startup | -
| component.java.debug | Active the remote debugging for the server process | false
| component.java.debug.port | If `component.java.debug` is true, the remote debugging port | 5005
|===

If you want to customize the server logs you can create a `$STUDIO_HOME/configuration/log4j2-components.xml` file
containing a link:https://logging.apache.org/log4j/2.x/[Log4j2] configuration.
