:toc:
:numbered:
:icons: font
:hide-uri-scheme:
:imagesdir: images
:outdir: ../assets
:jbake-type: page
:jbake-tags: documentation
:jbake-status: published

== Generating data?

Several data generator exists if you want to populate objects with a semantic a bit more evolved than a plain random string
like `commons-lang3`:

* https://github.com/Codearte/jfairy
* https://github.com/DiUS/java-faker
* https://github.com/andygibson/datafactory
* ...

A bit more advanced, these ones allow to bind directly generic data on a model - but data quality is not always there:

* https://github.com/devopsfolks/podam
* https://github.com/benas/random-beans
* ...

Note there are two main kind of implementations:

* the one using a _pattern_ and random generated data
* a set of precomputed data extrapolated to create new values

Check against your use case to know which one is the best.

NOTE: an interesting alternative to data generation is to import _real_ data and use Talend Studio to sanitize the data (remove sensitive information replacing them by generated data or anonymized data)
and just inject that file into the system.

If you are using JUnit 5, you can have a look to https://glytching.github.io/junit-extensions/randomBeans
which is pretty good on that topic.
