= Talend Component Kit best practices
:page-partial:
:keywords: best practices, checklist
:description: List of best practices for developing Talend components.

== Organizing your code

Some recommendations apply to the way component packages are organized:

. Make sure to create a `package-info.java file` with the component family/categories at the root of your component package:

[source,java]
----
@Components(family = "jdbc", categories = "Database")
package org.talend.sdk.component.jdbc;

import org.talend.sdk.component.api.component.Components;
----

[start=2]
. Create a package for the configuration.
. Create a package for the actions.
. Create a package for the component and one sub-package by type of component (input, output, processors, and so on).

== Configuring components

=== Serializing your configuration

It is recommended to serialize your configuration in order to be able to pass it through other components.

=== Input and output components

When building a new component, the first step is to identify the way it must be configured.

The two main concepts are:

1. The _DataStore_ which is the way you can access the backend.
2. The _DataSet_ which is the way you interact with the backend.

For example:

[options="header,autowidth"]
|====
| Example description | DataStore | DataSet
| Accessing a relational database like MySQL | JDBC driver, URL, username, password | Query to execute, row mapper, and so on.
| Accessing a file system | File pattern (or directory + file extension/prefix/...) | File format, buffer size, and so on.
|====

It is common to have the dataset including the datastore, because both are required to work. However, it is recommended to replace this pattern by defining both dataset and datastore in a higher level configuration model. For example:

[source,java]
----
@DataSet
public class MyDataSet {
    // ...
}

@DataStore
public class MyDataStore {
    // ...
}


public class MyComponentConfiguration {
    @Option
    private MyDataSet dataset;

    @Option
    private MyDataStore datastore;
}
----
==== About actions

Input and output components are particular because they can be linked to a set of actions. It is recommended to wire all the actions you can apply to ensure the consumers of your component can provide a rich experience to their users.

The most common actions are the following ones:

[cols="1,1,2,6,6"]
|====
| Type | Action | Description | Configuration example | Action example

| DataStore
| `@Checkable`
| Exposes a way to ensure the datastore/connection works
a|
[source,java]
----
@DataStore
@Checkable
public class JdbcDataStore
  implements Serializable {

  @Option
  private String driver;

  @Option
  private String url;

  @Option
  private String username;

  @Option
  private String password;
}

----
a|
[source,java]
----
@HealthCheck
public HealthCheckStatus healthCheck(@Option("datastore") JdbcDataStore datastore) {
    if (!doTest(dataStore)) {
        // often add an exception message mapping or equivalent
        return new HealthCheckStatus(Status.KO, "Test failed");
    }
    return new HealthCheckStatus(Status.KO, e.getMessage());
}
----

|====


==== Limitations

Until the studio integration is complete, it is recommended to limit processors to one input.

=== Processor components

Configuring processor components is simpler than configuring input and output components because it is specific for each component. For example, a mapper takes the mapping between the input and output models:

[source,java]
----
public class MappingConfiguration {
    @Option
    private Map<String, String> fieldsMapping;

    @Option
    private boolean ignoreCase;

    //...
}
----



== Handling UI interactions

It is recommended to provide as much information as possible to let the UI work with the data during its edition.

=== Validations

==== Light validations

Light validations are all the validations you can execute on the client side. They are listed in the <<component-configuration.adoc#documentation-ui-hints, UI hint>> section.

Use light validations first before going with custom validations because they are more efficient.

==== Custom validations

Custom validations enforce custom code to be executed, they are more heavy to process, so prefer using light validations when possible.

Define an action with the parameters needed for the validation and link the option you want to validate to this action.
For example, to validate a dataset for a JDBC driver:

[source,java]
----
// ...
public class JdbcDataStore
  implements Serializable {

  @Option
  @Validable("driver")
  private String driver;

  // ...
}

@AsyncValidation("driver")
public ValidationResult validateDriver(@Option("value") String driver) {
  if (findDriver(driver) != null) {
    return new ValidationResult(Status.OK, "Driver found");
  }
  return new ValidationResult(Status.KO, "Driver not found");
}
----

You can also define a Validable class and use it to validate a form by setting it on your whole configuration:

[source,java]
----
// Note: some parts of the API were removed for clarity

public class MyConfiguration {

  // a lot of @Options
}

public MyComponent {
    public MyComponent(@Validable("configuration") MyConfiguration config) {
        // ...
    }

    //...
}

@AsyncValidation("configuration")
public ValidationResult validateDriver(@Option("value") MyConfiguration configuration) {
  if (isValid(configuration)) {
    return new ValidationResult(Status.OK, "Configuration valid");
  }
  return new ValidationResult(Status.KO, "Driver not valid ${because ...}");
}
----

NOTE: The parameter binding of the validation method uses the same logic as the component configuration injection. Therefore, the `@Option` method specifies the prefix to use to reference a parameter. +
It is recommended to use `@Option("value")` until you know exactly why you don't use it. This way, the consumer can match the configuration model and just prefix it with `value.` to send the instance to validate.

=== Completion

It can be handy and user-friendly to provide completion on some fields.
For example, to define completion for available drivers:

[source,java]
----
// ...
public class JdbcDataStore
  implements Serializable {

  @Option
  @Completable("driver")
  private String driver;

  // ...
}

@Completion("driver")
public CompletionList findDrivers() {
    return new CompletionList(findDriverList());
}
----

=== Component representation

Each component must have its own icon:

[source,java]
----
@Icon(Icon.IconType.DB_INPUT)
@PartitionMapper(family = "jdbc", name = "input")
public class JdbcPartitionMapper
    implements Serializable {
}
----

TIP: You can use http://talend.surge.sh/icons/ to find the icon you want to use.

== Enforcing versioning on components

It is recommended to enforce the version of your component, event though it is not mandatory for the first version.

[source,java]
----
@Version(1)
@PartitionMapper(family = "jdbc", name = "input")
public class JdbcPartitionMapper
    implements Serializable {
}
----

If you break a configuration entry in a later version;  make sure to:

1. Upgrade the version.
2. Support a migration of the configuration.

[source,java]
----
@Version(value = 2, migrationHandler = JdbcPartitionMapper.Migrations.class)
@PartitionMapper(family = "jdbc", name = "input")
public class JdbcPartitionMapper
    implements Serializable {

    public static class Migrations implements MigrationHandler {
        // implement your migration
    }
}
----


== Testing components

Testing your components is critical. You can use unit and simple standalone JUnit tests, but it is also highly recommended to have Beam tests in order to make sure that your component works in Big Data.

ifeval::["{backend}" == "html5"]
[role="relatedlinks"]
== Related articles
- xref:tutorial-generate-project-using-starter.adoc[Generating a project using the starter]
- xref:component-define-input.adoc[Defining an input component]
- xref:component-define-processor-output.adoc[Defining a processor or output component]
- xref:component-configuration.adoc[Configuring a component]
- xref:component-registering.adoc[Registering a component]
- xref:component-internationalization.adoc[Internationalizing a component]
- xref:component-loading.adoc[Loading a component]
- xref:tutorial-configuration-sensitive-data.adoc[Masking sensitive data]
- xref:index-defining-services.adoc[Defining services]
- xref:index-testing-components.adoc[Testing components]
endif::[]
