= Defining component parameters and configuration
:page-partial:
:description: How to define the layout and configurable options of a component
:keywords: layout, option, field

The component configuration is defined in the `<component_name>Configuration.java` file of the package. It consists in defining the configurable part of the component that will be displayed in the UI.

To do that, you can specify parameters. When you import the project in your IDE, the parameters that you have specified in the starter are already present.

== Parameter name

Components are configured using their constructor parameters. All parameters can be marked with the `@Option` property, which lets you give a name to them.

For the name to be correct, you must follow these guidelines:

* Use a valid Java name.
* Do not include any `.` character in it.
* Do not start the name with a `$`.
* Defining a name is optional. If you don't set a specific name, it defaults to the bytecode name. This can require you to compile with a `-parameter` flag to avoid ending up with names such as `arg0`, `arg1`, and so on.

.Examples of option name:
[cols="<,^",options="header"]
|===
| Option name|Valid
| myName | icon:check[role="green"]
| my_name | icon:check[role="green"]
| my.name | icon:times[role="mediumvioletred"]
| $myName | icon:times[role="mediumvioletred"]
|===

== Parameter types

Parameter types can be _primitives_ or complex objects with fields decorated with `@Option` exactly like method parameters.

IMPORTANT: It is recommended to use simple models which can be serialized in order to ease serialized component implementations.

For example:

[source,java]
----
class FileFormat implements Serializable {
    @Option("type")
    private FileType type = FileType.CSV;

    @Option("max-records")
    private int maxRecords = 1024;
}

@PartitionMapper(name = "file-reader")
public MyFileReader(@Option("file-path") final File file,
                    @Option("file-format") final FileFormat format) {
    // ...
}
----

Using this kind of API makes the configuration extensible and component-oriented, which allows you to define all you need.

The instantiation of the parameters is done from the properties passed to the component.

=== Primitives

A primitive is a class which can be directly converted from a `String` to the expected type.

It includes all Java primitives, like the `String` type itself, but also all types with a `org.apache.xbean.propertyeditor.Converter`:

- `BigDecimal`
- `BigInteger`
- `File`
- `InetAddress`
- `ObjectName`
- `URI`
- `URL`
- `Pattern`

== Mapping complex objects

The conversion from property to object uses the Dot notation.

For example, assuming the method parameter was configured with `@Option("file")`:

[source,properties]
----
file.path = /home/user/input.csv
file.format = CSV
----

matches

[source,java]
----
public class FileOptions {
    @Option("path")
    private File path;

    @Option("format")
    private Format format;
}
----

=== List case

Lists rely on an indexed syntax to define their elements.

For example, assuming that the list parameter is named `files` and that the elements are of the  `FileOptions` type, you can define a list of two elements as follows:

[source,properties]
----
files[0].path = /home/user/input1.csv
files[0].format = CSV
files[1].path = /home/user/input2.xml
files[1].format = EXCEL
----

=== Map case

Similarly to the list case, the map uses `.key[index]` and `.value[index]` to represent its keys and values:

[source,properties]
----
// Map<String, FileOptions>
files.key[0] = first-file
files.value[0].path = /home/user/input1.csv
files.value[0].type = CSV
files.key[1] = second-file
files.value[1].path = /home/user/input2.xml
files.value[1].type = EXCEL
----

[source,properties]
----
// Map<FileOptions, String>
files.key[0].path = /home/user/input1.csv
files.key[0].type = CSV
files.value[0] = first-file
files.key[1].path = /home/user/input2.xml
files.key[1].type = EXCEL
files.value[1] = second-file
----

IMPORTANT: Avoid using the Map type. Instead, prefer configuring your component with an object if this is possible.

== Defining Constraints and validations on the configuration

You can use metadata to specify that a field is required or has a minimum size, and so on. This is done using the `validation` metadata in the `org.talend.sdk.component.api.configuration.constraint` package:

include::{partialsdir}/generated_constraints.adoc[]

IMPORTANT: When using the programmatic API, metadata is prefixed by `tcomp::`. This prefix is stripped in the web for convenience, and the table above uses the web keys.

Also note that these validations are executed before the runtime is started (when loading the component instance) and that the execution will fail if they don't pass.
If it breaks your application, you can disable that validation on the JVM by setting the system property `talend.component.configuration.validation.skip` to `true`.

[[dataset-and-datastore]]
== Marking a configuration as dataset or datastore

It is common to classify the incoming data. It is similar to tagging data with several types. Data can commonly be categorized as follows:

- Datastore: The data you need to connect to the backend.
- Dataset: A datastore coupled with the data you need to execute an action.

include::{partialsdir}/generated_configuration-types.adoc[]

IMPORTANT: The component family associated with a configuration type (datastore/dataset) is always the one related to the component using that configuration.

Those configuration types can be composed to provide one configuration item. For example, a dataset type often needs a datastore type to be provided. A datastore type (that provides the connection information) is used to create a dataset type.

Those configuration types are also used at design time to create shared configurations that can be stored and used at runtime.

For example, in the case of a relational database that supports JDBC:

- A datastore can be made of:
* a JDBC URL
* a username
* a password.
- A dataset can be made of:
* a datastore (that provides the data required to connect to the database)
* a table name
* data.

The component server scans all configuration types and returns a configuration type index. This index can be used for the integration into the targeted platforms (Studio, web applications, and so on).

The configuration type index is represented as a flat tree that contains all the configuration types, which themselves are represented as nodes and indexed by ID.

Every node can point to other nodes. This relation is represented as an array of edges that provides the child IDs.

As an illustration, a configuration type index for the example above can be defined as follows:

[source,json]
----
{nodes: {
             "idForDstore": { datastore:"datastore data", edges:[id:"idForDset"] },
             "idForDset":   { dataset:"dataset data" }
    }
}
----

== Defining links between properties

If you need to define a binding between properties, you can use a set of annotations:

include::{partialsdir}/generated_conditions.adoc[]

The target element location is specified as a relative path to the current location, using Unix path characters.
The configuration class delimiter is `/`. +
The parent configuration class is specified by `..`. +
Thus, `../targetProperty` denotes a property, which is located in the parent configuration class and is named `targetProperty`.

IMPORTANT: When using the programmatic API, metadata is prefixed with `tcomp::`. This prefix is stripped in the web for convenience, and the previous table uses the web keys.

[[documentation-ui-hints]]
== Adding hints about the rendering

In some cases, you may need to add metadata about the configuration to let the UI render that configuration properly. +
For example, a password value that must be hidden and not a simple clear input box. For these cases - if you want to change the UI rendering - you can use a particular set of annotations:

include::{partialsdir}/generated_ui.adoc[]

IMPORTANT: When using the programmatic API, metadata is prefixed with `tcomp::`. This prefix is stripped in the web for convenience, and the previous table uses the web keys.

You can also check xref:tutorial-configuration-sensitive-data.adoc[this example] about masking credentials.

Target support should cover `org.talend.core.model.process.EParameterFieldType` but you need to ensure that the web renderer is able to handle the same widgets.

ifeval::["{backend}" == "html5"]
[role="relatedlinks"]
== Related articles
- xref:methodology-creating-components.adoc[Methodology for creating components]
- xref:tutorial-generate-project-using-starter.adoc[Generating a project using the starter]
- xref:component-define-input.adoc[Defining an input component]
- xref:component-define-processor-output.adoc[Defining a processor or output component]
- xref:component-registering.adoc[Registering a component]
- xref:component-internationalization.adoc[Internationalizing a component]
- xref:component-loading.adoc[Loading a component]
- xref:tutorial-configuration-sensitive-data.adoc[Masking sensitive data]
- xref:best-practices.adoc[Best practices]
endif::[]
