= Configuring components

Component are configured through their constructor parameters. They can all be marked with `@Option`
which will let you give a name to parameters (if not it will use the bytecode name which can require you to compile with `-parameter` flag
to not have `arg0`, `arg1`, ... as names).

The parameter types can be _primitives_ or complex objects with fields decorated with `@Option` exactly like method parameters.

IMPORTANT: it is recommanded to use simple models which can be serialized by components to avoid headaches when implementing serialized components.

Here is an example:

[source,java]
----
class FileFormat implements Serializable {
    @Option("type")
    private FileType type = FileType.CSV;

    @Option("max-records")
    private int maxRecords = 1024;
}

@PartitionMapper(family = "demo", name = "file-reader")
public MyFileReader(@Option("file-path") final File file,
                    @Option("file-format") final FileFormat format) {
    // ...
}
----

Using this kind of API makes the configuration extensible and component oriented letting the user define all he needs.

The instantiation of the parameters is done from the properties passed to the component (see next part).

== Primitives

What is considered as a primitive in this mecanism is a class which can be directly converted from a `String` to the expected type.

It obviously includes all java primitives, `String` type itself but also all the types with a `org.apache.xbean.propertyeditor.Converter`.

This includes out of the box:

- `BigDecimal`
- `BigInteger`
- `File`
- `InetAddress`
- `ObjectName`
- `URI`
- `URL`
- `Pattern`

== Complex object mapping

The conversion from properties to object is using the dotted notation. For instance:

[source,properties]
----
file.path = /home/user/input.csv
file.format = CSV
----

will match

[source,java]
----
public class FileOptions {
    @Option("path")
    private File path;

    @Option("format")
    private Format format;
}
----

assuming the method parameter was configured with `@Option("file")`.

=== List case

Lists use the same syntax but to define their elements their rely on an indexed syntax. Assuming the list parameter is named `files`
and the elements are of  `FileOptions` type, here is how to define a list of 2 elements:

[source,properties]
----
files[0].path = /home/user/input1.csv
files[0].format = CSV
files[1].path = /home/user/input2.xml
files[2].format = EXCEL
----

=== Map case

Inspired from the list case, the map uses `.key[index]` and `.value[index]` to represent its key and values:

[source,properties]
----
// Map<String, FileOptions>
files.key[0] = first-file
files.value[0].path = /home/user/input1.csv
files.value[0].type = CSV
files.key[1] = second-file
files.value[1].path = /home/user/input2.xml
files.value[1].type = EXCEL
----

[source,properties]
----
// Map<FileOptions, String>
files.key[0].path = /home/user/input1.csv
files.key[0].type = CSV
files.value[0] = first-file
files.key[1].path = /home/user/input2.xml
files.key[1].type = EXCEL
files.value[1] = second-file
----

IMPORTANT: don't abuse of map type. If not needed for your configuration (= if you can configure your component
with an object) don't use it.

== Constraints and validation on the configuration/input

It is common to need to add as metadata a field is required, another has a minimum size etc. This is done with the
validation in `org.talend.sdk.component.api.configuration.constraint` package:

include::{partialsdir}/generated_constraints.adoc[]

IMPORTANT: using the programmatic API the metadata are prefixed by `tcomp::` but this prefix is stripped in the web for convenience,
the previous table uses the web keys.

== Marking a configuration as a particular type of data

It is common to classify the incoming data. You can see it as tagging them in several types. The most common ones
are the:

- datastore: all the data you need to connect to the backend
- dataset: a datastore coupled with all the data you need to execute an action

include::{partialsdir}/generated_configuration-types.adoc[]

IMPORTANT: the component family associated with a configuration type (datastore/dataset) is always the one related
to the component using that configuration.

Those configuration types can be composed to provide one configuration item. For example a dataset type will often need a datastore
type to be provided. and a datastore type (that provides the connection information) will be used to create a dataset type.

Those configuration types will also be used at design time to create shared configuration that can be stored and used at runtime.

For example, we can think about a relational database that support JDBC:

- A datastore may provide:
* jdbc url, username, password
- A dataset may be:
* datastore (that will provide the connection data to the database)
* table name, data []

The component server will scan all those configuration types and provide a configuration type index. This index can be used for the integration
into the targeted platforms (studio, web applications...)

The configuration type index is represented as a flat tree that contains all the configuration types represented as nodes and indexed by their ids.

Also, every node can point to other nodes. This relation is represented as an array of edges that provide the childes ids.

For example, a configuration type index for the above example will be:

[source,json]
----
{nodes: {
             "idForDstore": { datastore:"datastore data", edges:[id:"idForDset"] },
             "idForDset":   { dataset:"dataset data" }
    }
}
----

== Define links between properties

It can be needed to define a binding between properties, a set of annotations allows to do it:

include::{partialsdir}/generated_conditions.adoc[]

Target element location is specified as a relative path to current location using Unix path characters.
Configuration class delimiter is `/`. Parent configuration class is specified by `..`.
Thus `../targetProperty` denotes a property, which is located in parent configuration class and has name `targetProperty`.

IMPORTANT: using the programmatic API the metadata are prefixed by `tcomp::` but this prefix is stripped in the web for convenience,
the previous table uses the web keys.

[[documentation-ui-hints]]
== Add hints about the rendering based on configuration/component knowledge

In some case it can be needed to add some metadata about the configuration to let the UI render properly the configuration.
A simple example is a password value must be hidden and not a simple clear input box. For these cases - when the component developper
wants to influence the UI rendering - you can use a particular set of annotations:

include::{partialsdir}/generated_ui.adoc[]

IMPORTANT: using the programmatic API the metadata are prefixed by `tcomp::` but this prefix is stripped in the web for convenience,
the previous table uses the web keys.

NOTE: target support should cover `org.talend.core.model.process.EParameterFieldType` but we need to ensure web renderers is able to handle the same widgets.