= Registering components
:page-partial:

As you may have read in the <<getting-started.adoc#getting-started-first-quick-start, Getting Started>>, you need an annotation to register your component through the `family` method. Multiple components can use the same `family` value but the `family` + `name` pair must be unique for the system.

In order to share the same component family name and to avoid repetitions in all `family` methods,
you can use the `@Components` annotation on the root package of your component. it allows you to define the component family and the categories the component belongs to (`Misc` by default if not set).

Here is a sample `package-info.java`:

[source,java]
----
@Components(name = "my_component_family", categories = "My Category")
package org.talend.sdk.component.sample;

import org.talend.sdk.component.api.component.Components;
----

Another example with an existing component:

[source,java]
----
@Components(name = "Salesforce", categories = {"Business", "Cloud"})
package org.talend.sdk.component.sample;

import org.talend.sdk.component.api.component.Components;
----

== Components metadata

Components can require metadata to be integrated in Talend Studio or Cloud platforms.
Metadata is set on the component class and belongs to the `org.talend.sdk.component.api.component` package.

[options="header,autowidth"]
|====
| API | Description
| @Icon | Sets an icon key used to represent the component. You can use a custom key with the `custom()` method but the icon may not be rendered properly.
| @Version | Sets the component version. 1 by default.
|====

Example:

[source,java]
----
@Icon(FILE_XML_O)
@PartitionMapper(name = "jaxbInput")
public class JaxbPartitionMapper implements Serializable {
    // ...
}
----

=== Managing version configuration

If some changes impact the configuration, they can be managed through a migration handler at the *component* level (enabling trans-model migration support).

The `@Version` annotation supports a `migrationHandler` method which migrates the incoming configuration to the current model.

For example, if the `filepath` configuration entry from v1 changed to `location` in v2, you can remap the value in your `MigrationHandler` implementation.

A best practice is to split migrations into services that you can inject in the migration handler (through constructor) rather than managing all migrations directly in the handler. For example:

[source,java]
----
// full component code structure skipped for brievity, kept only migration part
@Version(value = 3, migrationHandler = MyComponent.Migrations.class)
public class MyComponent {
    // the component code...


    private interface VersionConfigurationHandler {
        Map<String, String> migrate(Map<String, String> incomingData);
    }

    public static class Migrations {
        private final List<VersionConfigurationHandler> handlers;

        // VersionConfigurationHandler implementations are decorated with @Service
        public Migrations(final List<VersionConfigurationHandler> migrations) {
            this.handlers = migrations;
            this.handlers.sort(/*some custom logic*/);
        }

        @Override
        public Map<String, String> migrate(int incomingVersion, Map<String, String> incomingData) {
            Map<String, String> out = incomingData;
            for (MigrationHandler handler : handlers) {
                out = handler.migrate(out);
            }
        }
    }
}
----

What is important to notice in this snippet is not the way the code is organized, but rather the fact that you can organize your migrations the way that best fits your component.

If you need to apply migrations in a specific order, make sure that they are sorted.

NOTE: Consider this API as a migration callback rather than a migration API. +
Adjust the migration code structure you need behind the `MigrationHandler`, based on your component requirements, using service injection.


=== @PartitionMapper

`@PartitionMapper` marks a partition mapper:

[source,java,indent=0,subs="verbatim,quotes,attributes"]
----
@PartitionMapper(family = "demo", name = "my_mapper")
public class MyMapper {
}
----

==== @Emitter

`@Emitter` is a shortcut for `@PartitionMapper` when you don't support distribution. It enforces an implicit partition mapper execution with an assessor size of 1 and a split returning itself.

[source,java,indent=0,subs="verbatim,quotes,attributes"]
----
@Emitter(family = "demo", name = "my_input")
public class MyInput {
}
----

=== @Processor

A method decorated with `@Processor` is considered as a producer factory:

[source,java,indent=0,subs="verbatim,quotes,attributes"]
----
@Processor(family = "demo", name = "my_processor")
public class MyProcessor {
}
----
