= Registering components
:page-partial:


Before implementing a component logic and configuration, you need to specify the family and the category it belongs to, as well as its name and a few other generic parameters.

Some of these parameters are handled at the project generation using the starter, but can still be accessed and updated later on.

== Component family and categories

The family and category of a component is automatically written in the `package-info.java` of the component package, using the `@Components` annotation. By default, these parameters are already configured in this file when you import your project in your IDE. Their value correspond to what was defined during the project definition with the starter.

Multiple components can share the same `family` and `category` value, but the `family` + `name` pair must be unique for the system.

A component can belong to one family only and to one or several categories. If not specified, the category defaults to `Misc`.

The `package-info.java` also defines the component family icon. You can learn how to customize this icon in xref:component-defining-custom-icon.adoc[this section].

Here is a sample `package-info.java`:

[source,java]
----
@Components(name = "my_component_family", categories = "My Category")
package org.talend.sdk.component.sample;

import org.talend.sdk.component.api.component.Components;
----

Another example with an existing component:

[source,java]
----
@Components(name = "Salesforce", categories = {"Business", "Cloud"})
package org.talend.sdk.component.sample;

import org.talend.sdk.component.api.component.Components;
----

== Component icon and version

Components can require metadata to be integrated in Talend Studio or Cloud platforms.
Metadata is set on the component class and belongs to the `org.talend.sdk.component.api.component` package.

When you generate your project and import it in your IDE, icon and version both come with a default value.

[options="header,autowidth"]
|====
| API | Description
| @Icon | Sets an icon key used to represent the component. You can use a custom key with the `custom()` method but the icon may not be rendered properly. +
Learn how to set a custom icon for your component in xref:component-defining-custom-icon.adoc[this section].
| @Version | Sets the component version. 1 by default. +
Learn how to manage different versions and migrations between your component versions in xref:component-versions-and-migration.adoc[this document].
|====

.Example
[source,java]
----
@Version(1)
@Icon(FILE_XML_O)
@PartitionMapper(name = "jaxbInput")
public class JaxbPartitionMapper implements Serializable {
    // ...
}
----


== Component types

The component type is declared in the component class. When you import your project generated from the starter in your IDE, the component type is already defined.


=== @PartitionMapper

`@PartitionMapper` marks a partition mapper:

[source,java,indent=0,subs="verbatim,quotes,attributes"]
----
@PartitionMapper(family = "demo", name = "my_mapper")
public class MyMapper {
}
----

==== @Emitter

`@Emitter` is a shortcut for `@PartitionMapper` when you don't support distribution. It enforces an implicit partition mapper execution with an assessor size of 1 and a split returning itself.

[source,java,indent=0,subs="verbatim,quotes,attributes"]
----
@Emitter(family = "demo", name = "my_input")
public class MyInput {
}
----

=== @Processor

A method decorated with `@Processor` is considered as a producer factory:

[source,java,indent=0,subs="verbatim,quotes,attributes"]
----
@Processor(family = "demo", name = "my_processor")
public class MyProcessor {
}
----

ifeval::["{backend}" == "html5"]
[role="relatedlinks"]
== Related articles
- xref:tutorial-generate-project-using-starter.adoc[Generating a project using the starter]
- xref:component-definition.adoc[Defining a component]
- xref:component-configuration.adoc[Configuring a component]
- xref:component-internationalization.adoc[Internationalizing a component]
- xref:component-loading.adoc[Loading a component]
- xref:tutorial-configuration-sensitive-data.adoc[Masking sensitive data]
- xref:best-practices.adoc[Best practices]
endif::[]
