= Talend Component Kit Developer Guide
:page-talend_documentationindex: true
:description: Talend Component Kit documentation for developers
:keywords: Talend Component Kit, Talend Component, documentation

Talend Component Kit is a framework designed to help you create Talend components for both Talend Studio and Cloud applications. +
This framework unifies the way components are built to ensure they are standardized and easy to deploy in different environments, as well as 'upgrade-compliant' as Talend applications are getting updated on a regular basis.

Start developing components by generating a project from the link:https://starter-toolkit.talend.io[Component Kit Starter] or by downloading the link:https://plugins.jetbrains.com/plugin/10558-talend-component-kit--intellij-plugin[Component Kit IntelliJ plugin].

ifeval::["{backend}" == "html5"]
ifeval::["{page-origin-refname}" == "master"]

IMPORTANT: This is a version under development which has not yet been deployed. You can however use it using the `-SNAPSHOT` version and Sonatype snapshot https://oss.sonatype.org/content/repositories/snapshots/[repository].

TIP: If you want a PDF version of that page you can find it in our snapshots: https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.talend.sdk.component&a=documentation&v={page-component-version}-SNAPSHOT&e=pdf&c=all-in-one[PDF].
endif::[]

ifeval::["{page-origin-refname}" != "master"]
NOTE: A complete PDF version of this documentation is available http://repo.apache.maven.org/maven2/org/talend/sdk/component/documentation/{page-component-version}/documentation-{page-component-version}-all-in-one.pdf[here].
endif::[]
endif::[]

[role="json"]
include::{partialsdir}/generated_documentationindex.adoc[]
