= Talend Component Kit Release Process
:page-partial:

Version: {docversion}

This page gives some hints about how to release the repository.

= Setup

== Gpg key

Before configuring Maven you need to have a GPG key.
Once you installed GPG, you can either import an existing key or generate
one using `gpg --gen-key`.

== Settings.xml

Then a few entries into your maven `settings.xml` are needed to provide the needed credentials
for the release. Here is the overall template:

[source,xml]
----
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="
            http://maven.apache.org/SETTINGS/1.0.0
            https://maven.apache.org/xsd/settings-1.0.0.xsd">
  <servers>
    <server>
      <id>ossrh</id>
      <username>${env.OSSRH_USER}</username>
      <password>${env.OSSRH_PASS}</password>
    </server>
    <server>
      <id>github</id>
      <username>${env.TLND_GITHUB_USER}</username>
      <password>${env.TLND_GITHUB_PASS}</password>
    </server>
    <server>
      <id>jira</id>
      <username>${env.TLND_JIRA_USER}</username>
      <password>${env.TLND_JIRA_PASS}</password>
    </server>
    <server>
      <id>blackduck</id>
      <username>${env.TLND_BLACKDUCK_USER}</username>
      <password>${env.TLND_BLACKDUCK_PASS}</password>
    </server>
  </servers>

  <profiles>
    <profile>
      <id>ossrh</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <properties>
        <additionalparam>-Xdoclint:none</additionalparam>
        <gpg.executable>gpg</gpg.executable>
        <gpg.defaultKeyring>false</gpg.defaultKeyring>
        <gpg.keyname>${env.GPG_KEYNAME}</gpg.keyname>
        <gpg.passphrase>${env.GPG_PASSPHRASE}</gpg.passphrase>
        <gpg.publicKeyring>${env.HOME}/.gpg/talend.pub.bin</gpg.publicKeyring>
        <gpg.secretKeyring>${env.HOME}/.gpg/talend.priv.bin</gpg.secretKeyring>
      </properties>
    </profile>
  </profiles>
</settings>
----

NOTE: all the environment variables should be either set in your environment or hardcoded inline. Note that it is more than highly recommanded
to use maven encryption: https://maven.apache.org/guides/mini/guide-encryption.html.

1. The OSSH variables are your Sonatype OSS repository credential with the permissions to deploy on org.talend.
If you don't have it already you can ask for one at https://issues.sonatype.org/projects/OSSRH using your talend address.
2. The GITHUB variables are your Github account credentials. It is mainly used to update the documentation.
3. The JIRA variables are your Talend account credentials with read permissions on https://jira.talendforge.org/projects/TCOMP/.
4. The Blackduck configuration is used for security scans.
5. The GPG variables reference the key you created in previous part.

== Clean up JIRA

The release contacts JIRA to create the release notes. It uses all `TCOMP` issues which have the label `changelog`.
Before any release don't forget to go through all issues of the version you will release and add/remove the label
depending the issue you want to appear into the release note.

== Do the release

IMPORTANT: at that stage we assume previous steps have been *done*.

Then, the release uses a standard Maven process, you should be able to do it in two steps:

[source,sh]
----
mvn release:prepare
mvn release:perform
----

Once these commands passed, you need to do/ensure:

1. The git tag corresponding to the release was pushed upstream (on github.com/Talend/component-runtime), if not,
execute `git push --follow-tags`?
2. Close and release the staging repository on Sonatype OSS (log in on https://oss.sonatype.org/, then hit `Staging Repositories` in the left pane,
select your repository and hit `Close` then `Release` on the top buttons).

== After the release

After a moment - it can take a few hours - the binaries will be available on central (http://repo.apache.maven.org/maven2/).
Don't forget to check it to ensure there was no issue during the release process.

You can also validate that the release deployed the new version (into the version menu) for the website.
