= Talend Component Kit Release Process
:page-partial:

Version: {page-component-version}

This page describes how to release the repository.

[[generate-gpg-key]]
== Installing GPG and generating a key

Before configuring Maven, you need to have a GPG key.
Install GPG and import an existing key or generate a new one using `gpg --gen-key`.

== Configuring settings.xml

Add the required credentials to your Maven `settings.xml` file for the release. The overall template is as follows:

[source,xml]
----
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="
            http://maven.apache.org/SETTINGS/1.0.0
            https://maven.apache.org/xsd/settings-1.0.0.xsd">
  <servers>
    <server>
      <id>ossrh</id>
      <username>${env.OSSRH_USER}</username>
      <password>${env.OSSRH_PASS}</password>
    </server>
    <server>
      <id>github</id>
      <username>${env.TLND_GITHUB_USER}</username>
      <password>${env.TLND_GITHUB_PASS}</password>
    </server>
    <server>
      <id>jira</id>
      <username>${env.TLND_JIRA_USER}</username>
      <password>${env.TLND_JIRA_PASS}</password>
    </server>
    <server>
      <id>blackduck</id>
      <username>${env.TLND_BLACKDUCK_USER}</username>
      <password>${env.TLND_BLACKDUCK_PASS}</password>
    </server>
  </servers>

  <profiles>
    <profile>
      <id>ossrh</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <properties>
        <additionalparam>-Xdoclint:none</additionalparam>
        <gpg.executable>gpg</gpg.executable>
        <gpg.defaultKeyring>false</gpg.defaultKeyring>
        <gpg.keyname>${env.GPG_KEYNAME}</gpg.keyname>
        <gpg.passphrase>${env.GPG_PASSPHRASE}</gpg.passphrase>
        <gpg.publicKeyring>${env.HOME}/.gpg/talend.pub.bin</gpg.publicKeyring>
        <gpg.secretKeyring>${env.HOME}/.gpg/talend.priv.bin</gpg.secretKeyring>
      </properties>
    </profile>
  </profiles>
</settings>
----

NOTE: All the environment variables should be either set in your environment or hardcoded inline. It is highly recommended to use Maven encryption: https://maven.apache.org/guides/mini/guide-encryption.html.

1. The OSSH variables are your Sonatype OSS repository credentials with the permissions to deploy on org.talend.
If you don't have them already, you can ask for them at https://issues.sonatype.org/projects/OSSRH using your Talend address.
2. The GitHub variables are your GitHub account credentials. they are mainly used to update the documentation.
3. The JIRA variables are your Talend account credentials with read permissions on https://jira.talendforge.org/projects/TCOMP/.
4. The Blackduck configuration is used for security scans.
5. The GPG variables reference the key mentioned in <<generate-gpg-key>>.

== Cleaning up JIRA

The release connects to JIRA to retrieve and create the release notes. It uses all `TCOMP` issues which have the `changelog` label.

Before any release, go through all the issues of the version to release and add or remove the `changelog` label depending on the issues that need to appear in the release notes.

== Releasing

IMPORTANT: At that stage, it is assumed that all previous steps have been *done*.

The release uses a standard Maven process. You should be able to do it in two steps:

[source,bash]
----
mvn release:prepare
mvn release:perform
----

Once these commands are passed, you need to:

. Rebuild the project which is now on the new SNAPSHOT version, in order to update site metadata and versions for the next iteration.
. Commit the diff.
. Make sure that the git tag corresponding to the release was pushed upstream (on github.com/Talend/component-runtime). If that is not the case, execute `git push --follow-tags`.

== After the release

After releasing - it can take up to a few hours - the binaries become available on Maven Central Repository (http://repo.apache.maven.org/maven2/).
Check it to make sure that there was no issue during the release process.

You can also validate that the release correctly deployed the new version from the Version menu of the website.
