= Defining a custom API
:page-partial:
:description: Extend the Talend Component Kit API with custom features
:keywords: component API

It is possible to extend the https://talend.github.io/component-runtime/apidocs/api/index.html[Component API] for custom front features.

What is important here is to keep in mind that you should do it only if it targets not portable components (only used by the Studio or Beam).

It is recommended to create a custom `xxxx-component-api` module with the new set of annotations.

== Extending the UI

To extend the UI, add an annotation that can be put on `@Option` fields, and that is decorated with `@Ui`.
All its members are then put in the metadata of the parameter. For example:

[source,java]
----
@Ui
@Target(TYPE)
@Retention(RUNTIME)
public @interface MyLayout {
}
----

ifeval::["{backend}" == "html5"]
[role="relatedlinks"]
== Related articles
- xref:services-internationalization.adoc[Internationalizing a service]
- xref:services-actions.adoc[Providing actions through a service]
- xref:services-built-in.adoc[Built-in services]
- xref:services-interceptors.adoc[Services and interceptors]
endif::[]
