= Internationalizing services
:page-partial:
:description: How to internationalize a service using Talend Component Kit
:keywords: service, internationalization

Internationalization requires following several best practices:

* Storing messages using `ResourceBundle` properties file in your component module.
* The location of the properties is in the same package than the related components and is named `Messages`. For example, `org.talend.demo.MyComponent` uses `org.talend.demo.Messages[locale].properties`.
* Use the internationalization API for your own messages.

== Internationalization API

The Internationalization API is the mechanism to use to internationalize your own messages in your own components.

The principle of the API is to design messages as methods returning `String` values and get back a template using a `ResourceBundle` named `Messages` and located in the same package than the interface that defines these methods.

To ensure your internationalization API is identified, you need to mark it with the `@Internationalized` annotation:

[source,java]
----
@Internationalized <1>
public interface Translator {

    String message();

    String templatizedMessage(String arg0, int arg1); <2>

    String localized(String arg0, @Language Locale locale); <3>

    String localized(String arg0, @Language String locale); <4>
}
----

<1> `@Internationalized` allows to mark a class as an internationalized service.
<2> You can pass parameters. The message uses the `MessageFormat` syntax to be resolved, based on the `ResourceBundle` template.
<3> You can use `@Language` on a `Locale` parameter to specify manually the locale to use. Note that a single value is used (the first parameter tagged as such).
<4> `@Language` also supports the `String` type.

ifeval::["{backend}" == "html5"]
[role="relatedlinks"]
== Related articles
- xref:services-actions.adoc[Providing actions through a service]
- xref:services-built-in.adoc[Built-in services]
- xref:services-interceptors.adoc[Services and interceptors]
- xref:services-custom-api.adoc[Defining a custom API]
endif::[]
