= Providing some actions for consumers/clients

In some cases you will desire to add some actions unrelated to the runtime. A simple example
is to enable clients - the users of the plugin/library - to test if a connection works. Even more concretely: _does my database is up?_.

To do so you need to define an `@Action` which is a method with a name (representing the event name) in a class decorated with `@Service`:

[source,java]
----
@Service
public class MyDbTester {
    @Action(family = "mycomp", "test")
    public Status doTest(final IncomingData data) {
        return ...;
    }
}
----

IMPORTANT: services are singleton so if you need some thread safety ensure they match that requirement. They
shouldn't store any state too (state is held by the component) since they can be serialized any time.

TIP: services are usable in components as well (matched by type) and allow to reuse some shared logic like a client. Here is a sample
with a service used to access files:

[source,java]
----
@Emitter(family = "sample", name = "reader")
public class PersonReader implements Serializable {
    // attributes skipped to be concise

    public PersonReader(@Option("file") final File file,
                        final FileService service) {
        this.file = file;
        this.service = service;
    }

    // use the service
    @PostConstruct
    public void open() throws FileNotFoundException {
        reader = service.createInput(file);
    }

}
----

TIP: service is passed to constructor automatically, it can be used as a bean. Only call of service's method is required.

== Particular action types

Some actions are that common and need a clear contract so they are defined as API first citizen, this is the case for wizards or healthchecks
for instance. Here is the list of all actions:

include::{partialsdir}/generated_actions.adoc[]