= Providing actions for consumers
:page-partial:
:description: How to define actions in a service
:keywords: service, action

In some cases you can need to add some actions that are not related to the runtime. For example,
enabling users of the plugin/library to test if a connection works properly.

To do so, you need to define an `@Action`, which is a method with a name (representing the event name), in a class decorated with `@Service`:

[source,java]
----
@Service
public class MyDbTester {
    @Action(family = "mycomp", "test")
    public Status doTest(final IncomingData data) {
        return ...;
    }
}
----

IMPORTANT: Services are singleton. If you need some thread safety, make sure that they match that requirement. Services should not store any status either because they can be serialized at any time. Status are held by the component.

Services can be used in components as well (matched by type). They allow to reuse some shared logic, like a client. Here is a sample with a service used to access files:

[source,java]
----
@Emitter(family = "sample", name = "reader")
public class PersonReader implements Serializable {
    // attributes skipped to be concise

    public PersonReader(@Option("file") final File file,
                        final FileService service) {
        this.file = file;
        this.service = service;
    }

    // use the service
    @PostConstruct
    public void open() throws FileNotFoundException {
        reader = service.createInput(file);
    }

}
----

The service is automatically passed to the constructor. It can be used as a bean. In that case, it is only necessary to call the service method.

== Particular action types

Some common actions need a clear contract so they are defined as API first-class citizen. For example, this is the case for wizards or health checks. Here is the list of the available actions:

include::{partialsdir}/generated_actions.adoc[]

== Internationalization

Internationalization is supported through the injection of the `$lang` parameter, which allows you to get the correct locale to use with an `@Internationalized` service:

[source]
----
public SuggestionValues findSuggestions(@Option("someParameter") final String param,
                                        @Option("$lang") final String lang) {
    return ...;
}
----

TIP: You can combine the `$lang` option with the `@Internationalized` and `@Language` parameters.

ifeval::["{backend}" == "html5"]
[role="relatedlinks"]
== Related articles
- xref:services-internationalization.adoc[Internationalizing a service]
- xref:services-built-in.adoc[Built-in services]
- xref:services-interceptors.adoc[Services and interceptors]
- xref:services-custom-api.adoc[Defining a custom API]
endif::[]
