= UiSpec Server
:toc:

The UiSpec server is a companion application for the Component Server.
It provides a client to the Component Server which serves UiSpec payload to integrate with the client JavaScript `UiForm` library.

== Coordinates

[source,xml]
----
<dependency>
  <groupId>org.talend.sdk.component</groupId>
  <artifactId>component-server-proxy</artifactId>
  <version>${server-proxy.version}</version>
</dependency>
----

== Configuring the UiSpec server

include::{partialsdir}/generated_proxy-server-configuration.adoc[]

=== Adding custom entries to the forms

As shown in the table above, you can customize the forms by type. The format reuses Talend Component Kit REST API (properties model) and defines two main types of extensions:

1. `prependProperties`: Lists all the models of properties added to the form *before* the actual underlying form.
2. `appendProperties`: Lists all the models of properties added to the form *after* the actual underlying form.

If you don't specify a name, the path is used to deduce the name automatically.

IMPORTANT: Always make sure to define a root object for these properties. Do not use dots in the `path` value. It is recommended to prefix it with a `$` character.

=== Adding custom converters (selecting the widget or rendering)

When developing a `org.talend.sdk.component.form.internal.converter.CustomPropertyConverter` CDI, the proxy adds it to the `UiSpecService` service and uses it with a high priority to convert the server model to a `UiSpec` model.

TIP: To make it a CDI bean, add `@Dependent` to the class and if you use the <<play-integration,Play integration>>, customize the bean array: `playx.cdi.beans.customs +=  {className: org.talend.myapp.MyConverter}.`

This allows to use a custom `@Ui` API and advanced modeling when specific to applications. +
Converters are sorted respecting to the `@Priority` value. If the annotation is missing, the priority defaults to `0`.

=== Client in Play

The client to use to connect to the Talend Component Kit server is the CXF client, using HttpClient HC (NIO) transport. When you use the Play module, it can be configured with its standard properties prefixed by `talend.component.proxy.`.

You can find more information on link:http://cxf.apache.org/docs/asynchronous-client-http-transport.html[CXF] website.

=== Defining a dropdown with all root configurations

The special `dynamic_values` action `builtin::roots` can be used for a dropdown filled with all available root types.

Here is a sample patch file:

[source,json]
----
{
  "prependProperties": [
    {
      "path": "$datasetMetadata",
      "type": "OBJECT"
    },
    {
      "path": "$datasetMetadata.type",
      "displayName": "Types",
      "type": "ENUM",
      "metadata": {
        "action::dynamic_values": "builtin::roots"
      }
    }
  ]
}
----

=== Reloading the form based on the selected root

The `builtin::root::reloadFromId` action, with the `jsonpatch` type,
allows to reload the whole form:

[source,json]
----
{
  "path": "$datasetMetadata.type",
  "displayName": "Types",
  "type": "STRING",
  "metadata": {
    "action::dynamic_values": "builtin::roots", <1>
    "action::reloadForm": "builtin::root::reloadFromId", <2>
    "action::reloadForm::parameters": "."
  }
}
----

<1> Prepopulating the dropdown with the list of datastores.
<2> On selection of a datastore, refreshing the form with the new parameters.

It is common to have a dropdown with the list of roots and to reload the form when one is selected.

For example, the `UIForm` part (JavaScript side) can be implemented as follows:

[source,javascript]
----
import kit from 'component-kit.js';

// ...

constructor(props) {
  super(props);

  this.state = {};
  this.trigger = kit.createTriggers({
    url: '/componentproxy/api/v1/actions/execute',
    customRegistry: {
      reloadForm: ({ body }) => { <1>
        const { _datasetMetadata } = this.state.uiSpec.properties;
        return {
          ...body, <2>
          properties: { _datasetMetadata }, <3>
        };
      }
    }
  });


  // ...
  }

// ...

onTrigger(event, payload) {
  return this.trigger(event, payload)
    .then(result => {
      if (result.properties || result.errors || result.uiSchema || result.jsonSchema) { <4>
        this.setState({
          uiSpec: {
            ...this.state.uiSpec,
            ...result,
          }
        });
      }
    });
}
----

<1> Adding a custom handler for the specific `reloadForm` action.
<2> Passing the `uiSchema` and `jsonSchema` to the next step in the response processing chain.
<3> Resetting the dynamic part of the form. Only the static part is kept.
<4> Merging back the result of the handler into the current state. You can use `redux` or `cmf`.

== HTTP API

include::{partialsdir}/generated_proxy-server-api.adoc[leveloffset=+2]

There are two ways to call the `save` endpoint. If you don't want to pass the form identifier and prefer to use a generic endpoint that simply passes the type of configuration you are configuring, then you need to modify your `enrichment` configuration to ensure that the form identifier is present and to specify which form field it is.

To do that, add the `proxyserver::formId` Boolean to the metadata:

[source,json]
----
{
  "path": "$datasetMetadata.type",
  "displayName": "Types",
  "type": "STRING",
  "metadata": {
    // other metadata as seen previously
    "proxyserver::formId": "true"
  }
}
----

IMPORTANT: Only the first property with `proxyserver::formId` set to `"true"` is used. The path cannot contain any array.

[[play-integration]]
== Integrating with Play

Thanks to https://github.com/rmannibucau/playx[Playx], you can deploy this server in a Play! application.

. Import the pre-configuration of the Play integration.

[source,xml]
----
<dependency>
  <groupId>org.talend.sdk.component</groupId>
  <artifactId>component-server-proxy-play</artifactId>
  <version>${server-proxy.version}</version>
</dependency>
----

[start=2]
. Configure the integration in your `application.conf` file:

[source,config]
----
include "conf/component-proxy.play.conf" <1>

talend.component.proxy { <2>
  server {
    base = "http://localhost:8080/api/v1"
  }
  processing {
    headers = """
X-ServiceName = proxy
X-ID = ${someRequestAttributeNameForTheId}
"""
    // ...
  }
}
----

<1> Importing the global configuration that maps the endpoints on `/componentproxy/*`.
<2> Customizing the configuration to specialize it for the current deployment.

=== If you are using Guice

The `org.talend.sdk.component.guice.ComponentUiSpecServerModule` Guice module allows to import `Services` from the server and to use some of them locally for the parts that are out of the scope of the endpoint delivery. For example:

- Converting `JsonObject` to `Map<String, String>` and the other way around.
- Getting the properties model for a configuration or component.

IMPORTANT: Use a `Provider<T>` injection to keep it lazy.

The server does not handle two layers. It is possible that you need to add:

1. Security.
2. Persistence.

For the security layer, it is recommended to create a Play filter that you configure before the proxy (`ServletFilter`). +
Make sure that you pass all contextual data in the request attributes to be able to get them back after.

For the persistence layer, the framework fires particular events (`OnPersist`, `OnEdit` and `OnFindById`) that you should observe in order to implement the persistence as you wish. +
Reusing the CDI context of the server just a plain CDI observer works, but if you used the Guice/CDI setup (using the Play module of the integration) you need to write Guice observers.

IMPORTANT: `OnPersist` needs to become identifier-aware of the created entity. Make sure to call `composeId`. In a similar way, `OnFindById` requires you to pass the found instance with `composeProperties()` and `composeFormId()`.

Optionally, you can implement `OnFindByFormId`, which allows to have completion for references. If your application does not allow to edit references, you can bypass this event. If you implement it, make sure to call `composeResult` no more than once.

[source,java]
----
@Singleton
public class PersistenceHandler {
    @Subscribe
    public void onPersist(final OnPersist event) {
        // do persist, ensure to call event.composeId(...)
    }

    @Subscribe
    public void onEdit(final OnEdit event) {
        // do update
    }

    @Subscribe
    public void onFind(final OnFindById event) {
        // do find
    }

    @Subscribe
    public void onFindByFormId(final OnFindByFormId event) {
        // do find
    }
}
----

NOTE: Deletion is not handled by the server because there is no encapsulation of any format at that moment.

== Configuring the server module

The server module contains several configurations that you can set in:

- Environment variables.
- System properties.
- A file located based on the `--component-configuration` CLI option.

include::{partialsdir}/generated_server-configuration.adoc[]
