= UiSpec Server

The UiSpec server is a companion application for the Component Server.
It provides a client to the Component Server which serves UiSpec payload to integrate with the client JavaScript `UiForm` library.

== Coordinates

[source,xml]
----
<dependency>
  <groupId>org.talend.sdk.component</groupId>
  <artifactId>component-server-proxy</artifactId>
  <version>${server-proxy.version}</version>
</dependency>
----

== Configuring the UiSpec server

include::{partialsdir}/generated_proxy-server-configuration.adoc[]

=== Adding custom entries to the forms

As shown in the table above, you can customize the forms by type. The format reuses Talend Component Kit REST API (properties model) and defines two main types of extensions:

1. `prependProperties`: Lists all the models of properties added to the form *before* the actual underlying form.
2. `appendProperties`: Lists all the models of properties added to the form *after* the actual underlying form.

If you don't specify a name, the path is used to deduce the name automatically.

IMPORTANT: Always make sure to define a root object for these properties. Do not use dots in the `path` value. It is recommended to prefix it with a `$` character.

=== Adding custom converters (selecting the widget or rendering)

When developing a `org.talend.sdk.component.form.internal.converter.CustomPropertyConverter` CDI, the proxy adds it to the `UiSpecService` service and uses it with a high priority to convert the server model to a `UiSpec` model.

TIP: To make it a CDI bean, add `@Dependent` to the class and if you use the <<play-integration,Play integration>>, customize the bean array: `playx.cdi.beans.customs +=  {className: org.talend.myapp.MyConverter}.`

This allows to use a custom `@Ui` API and advanced modeling when specific to applications. +
Converters are sorted respecting to the `@Priority` value. If the annotation is missing, the priority defaults to `0`.

=== Client in Play

The client to use to connect to the Talend Component Kit server is the CXF client, using HttpClient HC (NIO) transport. When you use the Play module, it can be configured with its standard properties prefixed by `talend.component.proxy.`.

You can find more information on link:http://cxf.apache.org/docs/asynchronous-client-http-transport.html[CXF] website.

=== Defining a dropdown with all root configurations

The special `dynamic_values` action `builtin::roots` can be used for a dropdown filled with all available root types.

Here is a sample patch file:

[source,json]
----
{
  "prependProperties": [
    {
      "path": "$datasetMetadata",
      "type": "OBJECT"
    },
    {
      "path": "$datasetMetadata.type",
      "displayName": "Types",
      "type": "ENUM",
      "metadata": {
        "action::dynamic_values": "builtin::roots"
      }
    }
  ]
}
----

=== Reloading the form based on the selected root

The `builtin::root::reloadFromId` action, with the `jsonpatch` type,
allows to reload the whole form:

[source,json]
----
{
  "path": "$datasetMetadata.type",
  "displayName": "Types",
  "type": "STRING",
  "metadata": {
    "action::dynamic_values": "builtin::roots", <1>
    "action::reloadForm": "builtin::root::reloadFromId", <2>
    "action::reloadForm::parameters": "."
  }
}
----

<1> Prepopulating the dropdown with the list of datastores.
<2> On selection of a datastore, refreshing the form with the new parameters.

It is common to have a dropdown with the list of roots and to reload the form when one is selected.

The client side (javascript) is now fully encapsulated in `ComponentForm` from `@talend/ui`.

== HTTP API

include::{partialsdir}/generated_proxy-server-api.adoc[leveloffset=+2]

There are two ways to call the `save` endpoint. If you don't want to pass the form identifier and prefer to use a generic endpoint that simply passes the type of configuration you are configuring, then you need to modify your `enrichment` configuration to ensure that the form identifier is present and to specify which form field it is.

To do that, add the `proxyserver::formId` Boolean to the metadata:

[source,json]
----
{
  "path": "$datasetMetadata.type",
  "displayName": "Types",
  "type": "STRING",
  "metadata": {
    // other metadata as seen previously
    "proxyserver::formId": "true"
  }
}
----

IMPORTANT: Only the first property with `proxyserver::formId` set to `"true"` is used. The path cannot contain any array.

== Configuring the server module

The server module contains several configurations that you can set in:

- Environment variables.
- System properties.
- A file located based on the `--component-configuration` CLI option.

include::{partialsdir}/generated_server-configuration.adoc[]
