= UiSpec Server
:toc:

The UiSpec server is a companion application for the Component Server.
It provides a client to the Component Server which serves UiSpec payload to integrate
with the client Javascript `UiForm` library.

== Coordinates

[source,xml]
----
<dependency>
  <groupId>org.talend.sdk.component</groupId>
  <artifactId>component-server-proxy</artifactId>
  <version>${server-proxy.version}</version>
</dependency>
----

== Configuration

include::{partialsdir}/generated_proxy-server-configuration.adoc[]

=== Add custom entries in the forms

As seen in the previous table you can customize the forms by type. The format is reusing Talend Component Kit
rest API (properties model) and defines two main types of extension:

1. `prependProperties`: which will list all the model of properties added to the form *before* the actual underlying form
2. `appendProperties`: which will list all the model of properties added to the form *after* the actual underlying form

Note that if you don't specify a name, the path is used to deduce the name automatically.

IMPORTANT: always ensure you define a root object (no dot in the `path` value) for these properties. It is recommanded
to prefix it with a `$`.

=== Add custom converters (select the widget or rendering)

Developping a CDI `org.talend.sdk.component.form.internal.converter.CustomPropertyConverter`, the proxy
will add it to the `UiSpecService` and use it with a high priority to convert the server model to a `UiSpec`.

TIP: to make it a CDI bean add `@Dependent` on the class and if you use play integration, custom beans array: `playx.cdi.beans.customs +=  {className: org.talend.myapp.MyConverter}`

This will allow to use custom `@Ui` API and advanced modelling when spceific to applications.

TIP: the converters are sorted respecting `@Priority` value, default value if missing is `0`.

=== Client in Play!

Also note that the client to connect to the Talend Component Kit server is
CXF client using HttpClient HC (NIO) transport. It can be configured with its standard properties
prefixed by `talend.component.proxy.` when you use the play module.

More info available on link:http://cxf.apache.org/docs/asynchronous-client-http-transport.html[CXF] website.

=== Dropdown with all root configurations

TIP: the special `dynamic_values` action `builtin::roots` can be used for a drop down which will
be filled with all available root types.

Here is a sample patch file:

[source,json]
----
{
  "prependProperties": [
    {
      "path": "$datasetMetadata",
      "type": "OBJECT"
    },
    {
      "path": "$datasetMetadata.type",
      "displayName": "Types",
      "type": "ENUM",
      "metadata": {
        "action::dynamic_values": "builtin::roots"
      }
    }
  ]
}
----

=== Reload the form based on the selected root

As a companion of previous action there is the `builtin::root::reloadFromId` action of type `jsonpatch` which
allows to reload the whole form:

[source,json]
----
{
  "path": "$datasetMetadata.type",
  "displayName": "Types",
  "type": "STRING",
  "metadata": {
    "action::dynamic_values": "builtin::roots", <1>
    "action::reloadForm": "builtin::root::reloadFromId", <2>
    "action::reloadForm::parameters": "."
  }
}
----

<1> Prepopulate the dropdown with the list of datastore
<2> On the selection of a datastore refresh the form with the new parameters

Here we use both to have a dropdown with the list of roots and to reload the form when one is selected.

Here is how the `UIForm` (javascript side) part can be implemented:

[source,javascript]
----
import kit from 'component-kit.js';

// ...

constructor(props) {
  super(props);

  this.state = {};
  this.trigger = kit.createTriggers({
    url: '/componentproxy/api/v1/actions/execute',
    customRegistry: {
      reloadForm: ({ body }) => { <1>
        const { _datasetMetadata } = this.state.uiSpec.properties;
        return {
          ...body, <2>
          properties: { _datasetMetadata }, <3>
        };
      }
    }
  });


  // ...
  }

// ...

onTrigger(event, payload) {
  return this.trigger(event, payload)
    .then(result => {
      if (result.properties || result.errors || result.uiSchema || result.jsonSchema) { <4>
        this.setState({
          uiSpec: {
            ...this.state.uiSpec,
            ...result,
          }
        });
      }
    });
}
----

<1> Add a custom handler for the specific `reloadForm` action
<2> Pass the `uiSchema` and `jsonSchema` back to the next step in the response processing chain
<3> Reset the dynamic part of the form (= keep only the static part)
<4> Merge back the result of the handler into the current state (you can use redux or cmf as well)

== HTTP API

include::{partialsdir}/generated_proxy-server-api.adoc[leveloffset=+1]

TIP: as you can see there are two ways to call save endpoint. If you don't want to pass the form identifier
and prefer to use a generic endpoint just passing the type of configuration you are configuring then you will
need to modify your enrichment configuration to ensure the form identier is present and to specify which form field it is.
To do that just add to the metadata the boolean `proxyserver::formId`:

[source,json]
----
{
  "path": "$datasetMetadata.type",
  "displayName": "Types",
  "type": "STRING",
  "metadata": {
    // other metadata as seen previously
    "proxyserver::formId": "true"
  }
}
----

IMPORTANT: only the first property with `proxyserver::formId` set to `"true"` is used. Also the path can't contain any array.

== Play Integration

Thanks to https://github.com/rmannibucau/playx[Playx] you can deploy this server
in a Play! application.

The first step is to import the play integration (which mainly imports pre-configuration):

[source,xml]
----
<dependency>
  <groupId>org.talend.sdk.component</groupId>
  <artifactId>component-server-proxy-play</artifactId>
  <version>${server-proxy.version}</version>
</dependency>
----

Then you can configure it in your `application.conf` - see configuration for more details:

[source,config]
----
include "conf/component-proxy.play.conf" <1>

talend.component.proxy { <2>
  server {
    base = "http://localhost:8080/api/v1"
  }
  processing {
    headers = """
X-ServiceName = proxy
X-ID = ${someRequestAttributeNameForTheId}
"""
    // ...
  }
}
----

<1> Imports the global configuration mapping the endpoints on `/componentproxy/*`
<2> Customize the configuration to specialize it for the current deployment

=== If you are using Guice

`org.talend.sdk.component.guice.ComponentUiSpecServerModule` Guice module allows
to import `Services` from the server and to use some of them locally for the part
out of scope of the endpoint delivery like:

- Converting `JsonObject` to `Map<String, String>` and the opposite
- Getting the properties model for a configuration or component (used in previous item)

IMPORTANT: it is important to use a `Provider<T>` injection to keep it lazy.

The server doesn't handle two layers you will likely need to add:

1. security
2. persistence

For the first layer it is recommended to create a Play filter you configure before the proxy one (`ServletFilter`).
You will need to ensure you pass all contextual data in the request attributes to be able to get them back after.

For the persistence, the framework will fire particular events `OnPersist`, `OnEdit` and `OnFindById` you should observe
to implement the persistence as you wish. If you reused the CDI context of the server just a plain CDI observer works
but if you used the Guice/CDI setup (using the play module of the integration) you will need to write Guice observers:

IMPORTANT: `OnPersist` will need to become identifier aware of the created entity, ensure to call `composeId` please. Similarly,
`OnFindById` requires you to pass the found instance with `composeProperties()` and `composeFormId()`.

Optionally you can implement `OnFindByFormId` which will allow to have completion for references. If your application
does not allow to edit references, you can bypass this event. If you implement it, ensure to call `composeResult` no more than once.

[source,java]
----
@Singleton
public class PersistenceHandler {
    @Subscribe
    public void onPersist(final OnPersist event) {
        // do persist, ensure to call event.composeId(...)
    }

    @Subscribe
    public void onEdit(final OnEdit event) {
        // do update
    }

    @Subscribe
    public void onFind(final OnFindById event) {
        // do find
    }

    @Subscribe
    public void onFindByFormId(final OnFindByFormId event) {
        // do find
    }
}
----

NOTE: the deletion is not handled by the server since there is not encapsulation of any format at that moment.


== Server Configuration

The server module contains several configuration you can set in:

- Environment variables
- System properties
- A file located based on the `--component-configuration` CLI option

include::{partialsdir}/generated_server-configuration.adoc[]
