= Built-in services
:page-partial:
:description: List of built-in services available with Talend Component Kit
:keywords: service

The framework provides built-in services that you can inject by type in components and actions.

== Lisf of built-in services

[role="table-striped table-hover table-ordered",options="header,autowidth"]
|===
| Type | Description
a| `org.talend.sdk.component.api.service.cache.LocalCache` | Provides a small abstraction to cache data that does not need to be recomputed very often. Commonly used by actions for UI interactions.
a| `org.talend.sdk.component.api.service.dependency.Resolver` a| Allows to resolve a dependency from its Maven coordinates.
a| `javax.json.bind.Jsonb` a| A JSON-B instance. If your model is static and you don't want to handle the serialization manually using JSON-P, you can inject that instance.
a| `javax.json.spi.JsonProvider` a| A JSON-P instance. Prefer other JSON-P instances if you don't exactly know why you use this one.
a| `javax.json.JsonBuilderFactory` a| A JSON-P instance. It is recommended to use this one instead of a custom one to optimize memory usage and speed.
a| `javax.json.JsonWriterFactory` a| A JSON-P instance. It is recommended to use this one instead of a custom one to optimize memory usage and speed.
a| `javax.json.JsonReaderFactory` a| A JSON-P instance. It is recommended to use this one instead of a custom one to optimize memory usage and speed.
a| `javax.json.stream.JsonParserFactory` a| A JSON-P instance. It is recommended to use this one instead of a custom one to optimize memory usage and speed.
a| `javax.json.stream.JsonGeneratorFactory` a| A JSON-P instance. It is recommended to use this one instead of a custom one to optimize memory usage and speed.
a| `org.talend.sdk.component.api.service.configuration.LocalConfiguration` a| Represents the local configuration that can be used during the design.
a| `org.talend.sdk.component.api.service.dependency.Resolver` a| Allows to resolve files from Maven coordinates (like `dependencies.txt` for component). Note that it assumes that the files are available in the component Maven repository.
a| `org.talend.sdk.component.api.service.injector.Injector` a| Utility to inject services in fields marked with `@Service`.
a| `org.talend.sdk.component.api.service.factory.ObjectFactory` a| Allows to instantiate an object from its class name and properties.

It is not recommended to use it for the runtime because the local configuration is usually different and the instances are distinct.

You can also use the local cache as an interceptor with `@Cached`

a| Every interface that extends `HttpClient` and that contains methods annotated with `@Request` a| Lets you define an HTTP client in a declarative manner using an annotated interface.

See the <<httpclient_usage>> for more details.

|===

IMPORTANT: All these *injected* services are serializable, which is important for big data environments. If you create the instances yourself, you cannot benefit from these features, nor from the memory optimization done by the runtime. Prefer reusing the framework instances over custom ones.

[[httpclient_usage]]
== Using HttpClient

The HttpClient usage is described in this section by using the REST API example below. It is assume that it requires a basic authentication header.

|===
| GET     `/api/records/{id}` | -
| POST    `/api/records`      | JSON payload to be created: `{"id":"some id", "data":"some data"}`
|===

To create an HTTP client that is able to consume the REST API above, you need to define an interface that extends `HttpClient`.

The `HttpClient` interface lets you set the `base` for the HTTP address that the client will hit.

The `base` is the part of the address that needs to be added to the request path to hit the API.

Every method annotated with `@Request` in the interface defines an HTTP request.
Every request can have a `@Codec` parameter that allows to encode or decode the request/response payloads.

TIP: You can ignore the encoding/decoding for `String` and `Void` payloads.

[source,java]
----
public interface APIClient extends HttpClient {
    @Request(path = "api/records/{id}", method = "GET")
    @Codec(decoder = RecordDecoder.class) //decoder =  decode returned data to Record class
    Record getRecord(@Header("Authorization") String basicAuth, @Path("id") int id);

    @Request(path = "api/records", method = "POST")
    @Codec(encoder = RecordEncoder.class, decoder = RecordDecoder.class) //encoder = encode record to fit request format (json in this example)
    Record createRecord(@Header("Authorization") String basicAuth, Record record);
}
----

IMPORTANT: The interface should extend `HttpClient`.

In the codec classes (that implement Encoder/Decoder), you can inject any of your service annotated with `@Service` or `@Internationalized` into the constructor.
Internationalization services can be useful to have internationalized messages for errors handling.

The interface can be injected into component classes or services to consume the defined API.
[source,java]
----
@Service
public class MyService {

    private APIClient client;

    public MyService(...,APIClient client){
        //...
        this.client = client;
        client.base("http://localhost:8080");// init the base of the api, ofen in a PostConstruct or init method
    }

    //...
    // Our get request
    Record rec =  client.getRecord("Basic MLFKG?VKFJ", 100);

    //...
    // Our post request
    Record newRecord = client.createRecord("Basic MLFKG?VKFJ", new Record());
}
----

NOTE: By default, `*/*+json` are mapped to JSON-P and `*/*+xml` to JAX-B if the model has a `@XmlRootElement` annotation.

=== Customizing HTTP client requests

For advanced cases, you can customize the `Connection` by directly using `@UseConfigurer` on the method. It calls your custom instance of `Configurer`. Note that you can use `@ConfigurerOption` in the method signature to pass some `Configurer` configurations.

For example, if you have the following `Configurer`:

[source,java]
----
public class BasicConfigurer implements Configurer {
    @Override
    public void configure(final Connection connection, final ConfigurerConfiguration configuration) {
        final String user = configuration.get("username", String.class);
        final String pwd = configuration.get("password", String.class);
        connection.withHeader(
            "Authorization",
            Base64.getEncoder().encodeToString((user + ':' + pwd).getBytes(StandardCharsets.UTF_8)));
    }
}
----

You can then set it on a method to automatically add the basic header with this kind of API usage:

[source,java]
----
public interface APIClient extends HttpClient {
    @Request(path = "...")
    @UseConfigurer(BasicConfigurer.class)
    Record findRecord(@ConfigurerOption("username") String user, @ConfigurerOption("password") String pwd);
}
----

ifeval::["{backend}" == "html5"]
[role="relatedlinks"]
== Related articles
- xref:services-internationalization.adoc[Internationalizing a service]
- xref:services-actions.adoc[Providing actions through a service]
- xref:services-interceptors.adoc[Services and interceptors]
- xref:services-custom-api.adoc[Defining a custom API]
endif::[]
