= Installing components using a CAR file
:page-partial:
:description: How to build a component archive that you can easily share and how to install the shared .car file in Talend Studio.
:keywords: deploy, install, car, .car, car-bundler, component archive, studio-integration

Components built using Talend Component Kit can be shared as component archives (.car). These CAR files are executable files allowing to easily deploy the components it contains to any compatible version of link:https://sourceforge.net/projects/talend-studio/[Talend Studio].

Component developers can generate .car files from their projects to share their components and make them available for other users, as detailed in xref:build-tools-maven.adoc[this document].

This document assumes that you have a component archive (.car) file and need to deploy it to Talend Studio.

== Deploying from the CAR file to Talend Studio

The component archive (.car) is executable and exposes the `studio-deploy` command which takes a Talend Studio home path as parameter. When executed, it installs the dependencies into the Studio and registers the component in your instance. For example:

[source,bash]
----
# for a studio
java -jar mycomponent.car studio-deploy /path/to/my/studio
or
java -jar mycomponent.car studio-deploy --location /path/to/my/studio

# for a m2 provisioning
java -jar mycomponent.car maven-deploy /path/to/.m2/repository
or
java -jar mycomponent.car maven-deploy --location /path/to/.m2/repository
----

You can also upload the dependencies to your Nexus server using the following command:

[source,bash]
----
java -jar mycomponent.car deploy-to-nexus --url <nexus url> --repo <repository name> --user <username> --pass <password> --threads <parallel threads number> --dir <temp directory>
----

In this command, Nexus URL and repository name are mandatory arguments. All other arguments are optional. If arguments contain spaces or special symbols, you need to quote the whole value of the argument. For example:

[source,bash]
----
--pass "Y0u will \ not G4iess i' ^"
----

== Deploying a component archive to a remote project from Talend Studio

Talend Studio allows you to share components you have created using Talend Component Kit to other users working on the same remote project.

NOTE: Remote projects are available with Enterprise versions of Talend Studio only. Also, note that *this feature has been removed* in Studio since 7.3 release.

Make sure you are connected to a remote project and the artifact repository for component sharing has been properly configured.

. On the toolbar of the Studio main window, click  or click *File* > *Edit Project Properties* from the menu bar to open the Project Settings dialog box.
. In the tree view of the dialog box, select *Repository Share* to open the corresponding view.
. Select the *Propagate components update to Artifact Repository* check box.
. In the Repository ID field, specify the artifact repository configured for component sharing, and then click *Check connection* to verify the connectivity.
. Click *Apply and Close* to validate the settings and close the dialog box.
. Create a folder named `patches` at the root of your Talend Studio installation directory, then copy the .car files of the components you want share to this folder.
. Restart your Talend Studio and connect to the remote project.

The components are deployed automatically to the repository and available in the Palette for other users when connected to a remote project with the same sharing repository configuration.


== Troubleshooting

*My custom component builds correctly but does not appear in Talend Studio, how to fix it?*
This issue can be caused by the icon specified in the component metadata.

* Make sure to specify a custom icon for the component and the component family.
* These custom icons must be in PNG format to be properly handled by Talend Studio.
* Remove SVG parameters from the `talend.component.server.icon.paths` property in the HTTP server configuration. Refer to xref:ref-server-configuration.adoc[this section].

Learn more about defining custom icons for components in xref:component-registering.adoc[this document].
