= Secrets/Passwords and Maven
:page-partial:
:description: Learn how to reuse Maven server files and credentials for testing purposes
:keywords: continuous integration, testing, password

You can reuse Maven `settings.xml` server files, including the encrypted ones.
`org.talend.sdk.component.maven.MavenDecrypter` allows yo to find a `username`/`password` from
a server identifier:

[source,java]
----
final MavenDecrypter decrypter = new MavenDecrypter();
final Server decrypted = decrypter.find("my-test-server");
// decrypted.getUsername();
// decrypted.getPassword();
----

It is very useful to avoid storing secrets and to perform tests on real systems on a continuous integration platform.

TIP: Even if you don't use Maven on the platform, you can generate the `settings.xml` and`settings-security.xml` files to use that feature. See https://maven.apache.org/guides/mini/guide-encryption.html for more details.

ifeval::["{backend}" == "html5"]
[role="relatedlinks"]
== Related articles
- xref:testing-best-practices.adoc[Component testing best practices]
- xref:index-sub-testing-runtime.adoc[Testing component runtime]
- xref:testing-beam.adoc[Beam testing]
- xref:testing-multiple-envs.adoc[Testing in multiple environments]
- xref:testing-generating-data.adoc[Generating data for testing]
- xref:services-pipeline.adoc[Simple/Test Pipeline API]
endif::[]
