[[component-runtime-http-junit]]
== component-runtime-http-junit
:page-partial:
:page-talend_skipindexation:

The HTTP JUnit module allows you to mock REST API very simply. The module coordinates are:

[source,xml]
----
<dependency>
  <groupId>org.talend.sdk.component</groupId>
  <artifactId>component-runtime-http-junit</artifactId>
  <version>${talend-component.version}</version>
  <scope>test</scope>
</dependency>
----

TIP: This module uses Apache Johnzon and Netty. If you have any conflict (in particular with Netty), you can add the `shaded` classifier to the dependency. This way, both dependencies are shaded, which avoids conflicts with your component.

It supports both JUnit 4 and JUnit 5. The concept is the exact same one: the extension/rule
is able to serve precomputed responses saved in the classpath.

You can plug your own `ResponseLocator` to map a request to a response, but the default implementation - which should be sufficient in most cases - looks in `talend/testing/http/<class name>_<method name>.json`. Note that you can also put it in `talend/testing/http/<request path>.json`.

=== JUnit 4

JUnit 4 setup is done through two rules:

* `JUnit4HttpApi`, which is starts the server.
* `JUnit4HttpApiPerMethodConfigurator`, which configures the server per test and also handles the capture mode.

IMPORTANT: If you don't use the `JUnit4HttpApiPerMethodConfigurator`, the capture feature is disabled and the per test mocking is not available.

.Test example

[source,java]
----
public class MyRESTApiTest {
    @ClassRule
    public static final JUnit4HttpApi API = new JUnit4HttpApi();

    @Rule
    public final JUnit4HttpApiPerMethodConfigurator configurator = new JUnit4HttpApiPerMethodConfigurator(API);

    @Test
    public void direct() throws Exception {
        // ... do your requests
    }
}
----

==== SSL

For tests using SSL-based services, you need to use `activeSsl()` on the `JUnit4HttpApi` rule.

You can access the client SSL socket factory through the API handler:

[source,java]
[subs=+quotes]
----
@ClassRule
public static final JUnit4HttpApi API = new JUnit4HttpApi()*.activeSsl()*;

@Test
public void test() throws Exception {
    final HttpsURLConnection connection = getHttpsConnection();
    connection.setSSLSocketFactory(API.getSslContext().getSocketFactory());
    // ....
}
----

==== Query Parameters

Sometimes the query parameters are sensitive and you don't want to store them when capturing.
In such cases, you can drop them from the captured data (`.json`) and the mock implementation will
be able to match the request ignoring the query parameters.

=== JUnit 5

JUnit 5 uses a JUnit 5 extension based on the `HttpApi` annotation that you can add to your test class. You can inject the test handler - which has some utilities for advanced cases - through `@HttpApiInject`:

[source,java]
----
@HttpApi
class JUnit5HttpApiTest {
    @HttpApiInject
    private HttpApiHandler<?> handler;

    @Test
    void getProxy() throws Exception {
        // .... do your requests
    }
}
----

NOTE: The injection is optional and the `@HttpApi` annotation allows you to configure several test behaviors.

==== SSL

For tests using SSL-based services, you need to use `@HttpApi(useSsl = true)`.

You can access the client SSL socket factory through the API handler:

[source,java]
[subs=+quotes]
----
@HttpApi*(useSsl = true)*
class MyHttpsApiTest {
    @HttpApiInject
    private HttpApiHandler<?> handler;

    @Test
    void test() throws Exception {
        final HttpsURLConnection connection = getHttpsConnection();
        connection.setSSLSocketFactory(handler.getSslContext().getSocketFactory());
        // ....
    }
}
----

=== Capturing mode

The strength of this implementation is to run a small proxy server and to auto-configure the JVM:
`http[s].proxyHost`, `http[s].proxyPort`, `HttpsURLConnection#defaultSSLSocketFactory` and `SSLContext#default` are auto-configured to work out-of-the-box with the proxy.

It allows you to keep the native and real URLs in your tests. For example, the following test is valid:

[source,java]
----
public class GoogleTest {
    @ClassRule
    public static final JUnit4HttpApi API = new JUnit4HttpApi();

    @Rule
    public final JUnit4HttpApiPerMethodConfigurator configurator = new JUnit4HttpApiPerMethodConfigurator(API);

    @Test
    public void google() throws Exception {
        assertEquals(HttpURLConnection.HTTP_OK, get("https://google.fr?q=Talend"));
    }

    private int get(final String uri) throws Exception {
        // do the GET request, skipped for brievity
    }
}
----

If you execute this test, it fails with an HTTP 400 error because the proxy does not find the mocked response. +
You can create it manually, as described in <<component-runtime-http-junit>>, but you can also set the `talend.junit.http.capture` property to the folder storing the captures. It must be the root folder and not the folder where the JSON files are located (not prefixed by `talend/testing/http` by default).

In most cases, use `src/test/resources`. If `new File("src/test/resources")` resolves the valid folder when executing your test (Maven default), then you can just set the system property to `true`. Otherwise, you need to adjust accordingly the system property value.

When the tests run with this system property, the testing framework creates the correct mock response files. After that, you can remove the system property. The tests will still pass, using `google.com`, even if you disconnect your machine from the Internet.

=== Passthrough mode

If you set the `talend.junit.http.passthrough` system property to `true`, the server acts as a proxy and executes each request to the actual server - similarly to the capturing mode.

=== JUnit 5 and capture names

With its `@ParameterizedTest`, you can want to customize the name of the output file for JUnit 5 based captures/mocks.
Concretely you want to ensure the replay of the same method with different data lead to different mock files.
By default the framework will use the display name of the test to specialize it but it is not always very friendly.
If you want some more advanced control over the name you can use `@HttpApiName("myCapture.json")` on the test method.
To parameterize the name using `@HttpApiName`, you can use the placeholders `${class}` and `${method}` which represents
the declaring class and method name, and `${displayName}` which represents the method name.

Here is an example to use the same capture file for all repeated test:

[source,java]
----
@HttpApiName("${class}_${method}")
@RepeatedTest(5)
void run() throws Exception {
    // ...
}
----

And here, the same example but using different files for each repetition:

[source,java]
----
@HttpApiName("${class}_${method}_${displayName}")
@RepeatedTest(5)
void run() throws Exception {
    // ...
}
----
