= Generating data
:page-partial:
:description: Learn how to generate data for testing components developed with Talend Component Kit
:keywords: test, generate data

Several data generators exist if you want to populate objects with a semantic that is more evolved than a plain random string like `commons-lang3`:

* https://github.com/Codearte/jfairy
* https://github.com/DiUS/java-faker
* https://github.com/andygibson/datafactory
* etc.

Even more advanced, the following generators allow to directly bind generic data on a model. However, data quality is not always optimal:

* https://github.com/devopsfolks/podam
* https://github.com/benas/random-beans
* etc.

There are two main kinds of implementation:

* Implementations using a _pattern_ and random generated data.
* Implementations using a set of precomputed data extrapolated to create new values.

Check your use case to know which one fits best.

NOTE: An alternative to data generation can be to import _real_ data and use Talend Studio to sanitize the data, by removing sensitive information and replacing it with generated or anonymized data. Then you just need to inject that file into the system.

If you are using JUnit 5, you can have a look at https://glytching.github.io/junit-extensions/randomBeans.

ifeval::["{backend}" == "html5"]
[role="relatedlinks"]
== Related articles
- xref:testing-best-practices.adoc[Component testing best practices]
- xref:index-sub-testing-runtime.adoc[Testing component runtime]
- xref:testing-beam.adoc[Beam testing]
- xref:testing-multiple-envs.adoc[Testing in multiple environments]
- xref:testing-maven-passwords.adoc[Reusing Maven credentials]
- xref:services-pipeline.adoc[Simple/Test Pipeline API]
endif::[]
