= Testing best practices
:page-partial:
:description: Learn the best practices for testing components developed with Talend Component Kit
:keywords: test

This section mainly concerns tools that can be used with JUnit. You can use most of these best practices with TestNG as well.

== Parameterized tests

Parameterized tests are a great solution to repeat the same test multiple times. This method of testing requires defining a test scenario (`I test function F`) and making the input/output data dynamic.

=== JUnit 4

Here is a test example, which validates a connection URI using `ConnectionService`:

[source,java]
----
public class MyConnectionURITest {
    @Test
    public void checkMySQL() {
        assertTrue(new ConnectionService().isValid("jdbc:mysql://localhost:3306/mysql"));
    }

    @Test
    public void checkOracle() {
        assertTrue(new ConnectionService().isValid("jdbc:oracle:thin:@//myhost:1521/oracle"));
    }
}
----

The testing method is always the same. Only values are changing. It can therefore be rewritten using JUnit `Parameterized` runner, as follows:

[source,java]
----
@RunWith(Parameterized.class) <1>
public class MyConnectionURITest {

    @Parameterized.Parameters(name = "{0}") <2>
    public static Iterable<String> uris() { <3>
        return asList(
            "jdbc:mysql://localhost:3306/mysql",
            "jdbc:oracle:thin:@//myhost:1521/oracle");
    }

    @Parameterized.Parameter <4>
    public String uri;

    @Test
    public void isValid() { <5>
        assertNotNull(uri);
    }
}
----

<1> `Parameterized` is the runner that understands `@Parameters` and how to use it. If needed, you can generate random data here.
<2> By default the name of the executed test is the index of the data. Here, it is customized using the first `toString()` parameter value to have something more readable.
<3> The `@Parameters` method must be static and return an array or iterable of the data used by the tests.
<4> You can then inject the current data using the `@Parameter` annotation. It can take a parameter if you use an array of array instead of an iterable of object in `@Parameterized`. You can select which item you want to inject.
<5> The `@Test` method is executed using the contextual data. In this sample, it gets executed twice with the two specified URIs.

TIP: You don't have to define a single `@Test` method. If you define multiple methods, each of them is executed with all the data. For example, if another test is added to the previous example, four tests are executed - 2 per data).

=== JUnit 5

With JUnit 5, parameterized tests are easier to use. The full documentation is available at http://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests.

The main difference with JUnit 4 is that you can also define inline that the test method is a parameterized test as well as the values to use:

[source,java]
----
@ParameterizedTest
@ValueSource(strings = { "racecar", "radar", "able was I ere I saw elba" })
void mytest(String currentValue) {
    // do test
}
----

However, you can still use the previous behavior with a method binding configuration:

[source,java]
----
@ParameterizedTest
@MethodSource("stringProvider")
void mytest(String currentValue) {
    // do test
}

static Stream<String> stringProvider() {
    return Stream.of("foo", "bar");
}
----

This last option allows you to inject any type of value - not only primitives - which is common to define scenarios.

IMPORTANT: Add the `junit-jupiter-params` dependency to benefit from this feature.

ifeval::["{backend}" == "html5"]
[role="relatedlinks"]
== Related articles
- xref:index-sub-testing-runtime.adoc[Testing component runtime]
- xref:testing-beam.adoc[Beam testing]
- xref:testing-multiple-envs.adoc[Testing in multiple environments]
- xref:testing-maven-passwords.adoc[Reusing Maven credentials]
- xref:testing-generating-data.adoc[Generating data for testing]
- xref:services-pipeline.adoc[Simple/Test Pipeline API]
endif::[]
