== component-runtime-http-junit
:page-partial:

The HTTP JUnit module allows you to mock REST API very easily. Here are its coordinates:

[source,xml]
----
<dependency>
  <groupId>org.talend.sdk.component</groupId>
  <artifactId>component-runtime-junit</artifactId>
  <version>${talend-component.version}</version>
  <scope>test</scope>
</dependency>
----

TIP: this module uses Apache Johnzon and Netty, if you have any conflict (in particular with netty) you can add the classifier `shaded`
to the dependency and the two dependencies are shaded avoiding the conflicts with your component.

It supports JUnit 4 and JUnit 5 as well but the overall concept is the exact same one: the extension/rule
is able to serve precomputed responses saved in the classpath.

You can plug your own `ResponseLocator` to map a request to a response but the default implementation - which should be sufficient
in most cases - will look in `talend/testing/http/<class name>_<method name>.json`. Note that you can also put it
in `talend/testing/http/<request path>.json`.

=== JUnit 4

JUnit 4 setup is done through two rules: `JUnit4HttpApi` which is responsible to start the server and `JUnit4HttpApiPerMethodConfigurator`
which is responsible to configure the server per test and also handle the capture mode (see later).

IMPORTANT: if you don't use the `JUnit4HttpApiPerMethodConfigurator`, the capture feature will be deactivated and the per test mocking will not be available.

Most of the test will look like:

[source,java]
----
public class MyRESTApiTest {
    @ClassRule
    public static final JUnit4HttpApi API = new JUnit4HttpApi();

    @Rule
    public final JUnit4HttpApiPerMethodConfigurator configurator = new JUnit4HttpApiPerMethodConfigurator(API);

    @Test
    public void direct() throws Exception {
        // ... do your requests
    }
}
----

==== SSL

For tests using SSL based services, you will need to use `activeSsl()` on the `JUnit4HttpApi` rule.

If you need to access the server ssl socket factory you can do it from the `HttpApiHandler` (the rule):

[source,java]
[subs=+quotes]
----
@ClassRule
public static final JUnit4HttpApi API = new JUnit4HttpApi()*.activeSsl()*;

@Test
public void test() throws Exception {
    final HttpsURLConnection connection = getHttpsConnection();
    connection.setSSLSocketFactory(API.getSslContext().getSocketFactory());
    // ....
}
----

=== JUnit 5

JUnit 5 uses a JUnit 5 extension based on the `HttpApi` annotation you can put on your test class. You can inject
the test handler (which has some utilities for advanced cases) through `@HttpApiInject`:

[source,java]
----
@HttpApi
class JUnit5HttpApiTest {
    @HttpApiInject
    private HttpApiHandler<?> handler;

    @Test
    void getProxy() throws Exception {
        // .... do your requests
    }
}
----

NOTE: the injection is optional and the `@HttpApi` allows you to configure several behaviors of the test.

==== SSL

For tests using SSL based services, you will need to use `@HttpApi(useSsl = true)`.

You can access the client SSL socket factory through the api handler:

[source,java]
[subs=+quotes]
----
@HttpApi*(useSsl = true)*
class MyHttpsApiTest {
    @HttpApiInject
    private HttpApiHandler<?> handler;

    @Test
    void test() throws Exception {
        final HttpsURLConnection connection = getHttpsConnection();
        connection.setSSLSocketFactory(handler.getSslContext().getSocketFactory());
        // ....
    }
}
----

=== Capturing mode

The strength of this implementation is to run a small proxy server and auto configure the JVM:
`http[s].proxyHost`, `http[s].proxyPort`, `HttpsURLConnection#defaultSSLSocketFactory` and `SSLContext#default`
are auto configured to work out of the box with the proxy.

It allows you to keep in your tests the native and real URLs. For instance this test is perfectly valid:

[source,java]
----
public class GoogleTest {
    @ClassRule
    public static final JUnit4HttpApi API = new JUnit4HttpApi();

    @Rule
    public final JUnit4HttpApiPerMethodConfigurator configurator = new JUnit4HttpApiPerMethodConfigurator(API);

    @Test
    public void google() throws Exception {
        assertEquals(HttpURLConnection.HTTP_OK, get("https://google.fr?q=Talend"));
    }

    private int get(final String uri) throws Exception {
        // do the GET request, skipped for brievity
    }
}
----

If you execute this test, it will fail with a HTTP 400 because the proxy doesn't find the mocked response.
You can create it manually as seen in the introduction of the module but you can also set the property `talend.junit.http.capture`
to the folder where to store the captures. It must be the root folder and not the folder where the json are (ie not prefixed by `talend/testing/http` by default).

Generally you will want to use `src/test/resources`. If `new File("src/test/resources")` resolves to the valid folder when executing your test (Maven default),
then you can just set the system property to true, otherwise you need to adjust accordingly the system property value.

Once you ran the tests with this system property, the testing framework will have created the correct mock response files and you can
remove the system property. The test will still pass, using `google.com`...even if you disconnect your machine from the internet.

The rule (extension) is doing all the work for you :).

=== Passthrough mode

Setting `talend.junit.http.passthrough` system property to `true`, the server will just be a proxy and will execute each request
to the actual server - like in capturing mode.
