= Testing a component
:page-partial:
:description: Example of input component testing using Talend Component Kit
:keywords: tutorial, example, test, hazelcast

[[tutorial-test-your-components]]
This tutorial focuses on writing unit tests for the input component that was created in this xref:tutorial-create-an-input-component.adoc[previous tutorial].

This tutorial covers:

1. How to load components in a unit test.
2. How to create a job pipeline.
3. How to run the test in standalone mode.

The test class is as follows:
[source,java,indent=0,subs="verbatim,quotes,attributes",]
----
public class HazelcastMapperTest {

    @ClassRule
    public static final SimpleComponentRule COMPONENTS = new SimpleComponentRule(HazelcastMapperTest.class
                                                                                    .getPackage().getName()); <1>

    private static HazelcastInstance instance; <2>

    @BeforeClass
    public static void startInstanceWithData() { <3>
        instance = Hazelcast.newHazelcastInstance();
        final IMap<Object, Object> map = instance.getMap(HazelcastMapperTest.class.getSimpleName());
        IntStream.range(0, 100).forEach(i -> map.put("test_" + i, "value #" + i));
    }

    @AfterClass
    public static void stopInstance() { <4>
        instance.getLifecycleService().shutdown();
    }

    @Test
    public void run() { <5>
        Job.components() <6>
                .component("source", "Hazelcast://Input?configuration.mapName=" + HazelcastMapperTest.class.getSimpleName())
                .component("output", "test://collector")
            .connections()
                .from("source").to("output")
            .build()
            .run();

        final List<JsonObject> outputs = COMPONENTS.getCollectedData(JsonObject.class); <7>
        assertEquals(100, outputs.size());
    }
}
----
<1> `SimpleComponentRule` is a JUnit rule that lets you load your component from a package. This rule also provides some test components like `emitter` and `collector`. Learn more about JUnit in xref:testing-junit.adoc#_component_runtime_junit[this section].
<2> Using an embedded Hazelcast instance to test the input component.
<3> Creating an embedded Hazelcast instance and filling it with some test data. A map with the name of the test class is created and data is added to it.
<4> Cleaning up the instance after the end of the tests.
<5> Defining the unit test. It first creates a job pipeline that uses our input component.
<6> The xref:services-pipeline.adoc[pipeline builder] `Job` is used to create a job. It contains two components: the input component and the test collector component. The input component is connected to the collector component. Then the job is built and ran locally.
<7> After the job has finished running. The `COMPONENTS` rule instance is used to get the collected data from the `collector` component.
Once this is done, it is possible to do some assertion on the collected data.
