= What is a Talend Component
:page-partial:
:description: Talend Component Kit helps you creating Talend components
:keywords: component, definition

Basically, a component (or connector) is a functional piece that performs a single operation from a Talend application. For example, *tMysqlInput* extracts data from a MySQL table, *tFilterRow* filters data based on a condition.

Physically, a component is a set of files stored within a folder named after the component name. All native components are located in the `<Talend Studio installation dir>/plugins/org.talend.designer.components.localprovider_[version]/components` directory. Each component is a sub-folder under this directory, the folder name is the component name.

Graphically, a component is an icon that you can drag and drop from the Palette to the workspace.

Technically, a component is a snippet of generated Java code that is part of a Job which is a Java class. A Job is made of one or more components or connectors. The job name will be the class name and each component in a job will be translated to a snippet of generated Java code. The Java code will be compiled automatically when you save the job.

*Talend Component Kit* helps you creating your own components.

ifeval::["{backend}" == "html5"]
[role="relatedlinks"]
== Related articles
- xref:tck-framework-overview.adoc[Talend Component Kit framework overview]
- xref:methodology-creating-components.adoc[Methodology for creating components]
- xref:component-execution.adoc[General component execution logic]
endif::[]
