#!/usr/bin/env python3
"""Appends (idempotently) the 'Unverified items' table to 10-appendix/known-discrepancies.md."""
import re, os, glob
HERE = os.path.dirname(os.path.abspath(__file__)); DOC = os.path.abspath(os.path.join(HERE, '..'))
OUT = os.path.join(DOC, '10-appendix', 'known-discrepancies.md')
pat = re.compile(r'\(\s*(?:unverified|inferred)[^)]*\)|\*\(?inferred\)?\*|\bunverified\b|\binferred\b', re.I)
skip = re.compile(r'are marked|Marking\*\*|Unknown facts|Inferences are marked|marked `|\(inferred\)` =|This list is generated|Marker:|Statements marked|= deduced|\(moved\)|^\| D\d\d |schema (is )?inferred|inferred from the (calls|added entries)|Dynamic schema', re.I)
files = [f for f in sorted(glob.glob(DOC + '/*.md') + glob.glob(DOC + '/02-feature-catalog/*.md') + glob.glob(DOC + '/10-appendix/*.md')) if not f.endswith('known-discrepancies.md')]
rows = []
for f in files:
    rel = os.path.relpath(f, os.path.join(DOC, '10-appendix')).replace('\\', '/')
    head = ''
    for ln in open(f, encoding='utf-8').read().split('\n'):
        if re.match(r'#{2,3} ', ln): head = re.sub(r'[`*|]', '', ln.lstrip('# ')).strip()[:70]
        if not pat.search(ln) or skip.search(ln): continue
        # split line into segments and keep those containing a marker
        for seg in ([ln.strip().strip('|')] if ln.startswith('|') else re.split(r'(?<=[.;]) (?=[A-Z(`*])', ln)):
            m = pat.search(seg)
            if not m or skip.search(seg): continue
            kind = 'I' if re.search('infer', m.group(0), re.I) else 'U'
            s = re.sub(r'\s+', ' ', seg).strip(' |-*')
            s = s.replace('|', '\\|')
            if len(s) > 230:
                a = max(0, m.start() - 150); s = ('...' if a else '') + s[a:a + 230].strip() + '...'
            rows.append((rel, head.replace('|', '\\|'), kind, s))
seen, uniq = set(), []
for r in rows:
    k = (r[0], r[2], r[3])
    if k in seen: continue
    seen.add(k); uniq.append(r)
txt = open(OUT, encoding='utf-8').read()
marker = 'This list is generated by `.work/unverified.py`.\n'
txt = txt[:txt.index(marker) + len(marker)] + '\n'
txt += f'{len(uniq)} statements ({sum(1 for r in uniq if r[2]=="U")} unverified, {sum(1 for r in uniq if r[2]=="I")} inferred).\n\n| # | File | Section | Marker | Statement |\n|---|---|---|---|---|\n'
for i, (rel, head, kind, s) in enumerate(uniq, 1):
    txt += f'| {i} | [{os.path.basename(rel)}]({rel}) | {head} | {kind} | {s} |\n'
open(OUT, 'w', encoding='utf-8', newline='\n').write(txt)
print(len(uniq), 'unverified/inferred statements')
