= Release Notes - 1.1.9 - Talend Component Kit
:page-partial:
:page-talend_skipindexation:

To get the full list of changes and bug fixes included in this new version, check the xref:changelog.adoc[changelogs].

== Component Kit Starter

Several enhancements were made to the link:https://starter-toolkit.talend.io/[Component Kit Starter]:

* Enabling the I/O mode now automatically pre-configures a default datastore and dataset, as well as default Input and Output components.
* Adding a new component to your project now presents more clearly the different choices available.
* The Starter now supports Java types (names) starting with a lowercase value.

== Repositories

The `component-api` repository has been merged into the `component-runtime` repository, which is now the unique GitHub repository for Talend Component Kit.

== Dependencies updates

Several dependencies have been upgraded to a newer version, including:

* Apache Beam 2.12.0
* Geronimo OpenAPI 1.0.8
* Icon bundle version 3.1.0
* Jupiter 5.4.2
* Tomcat 9.0.19
* asciidoctor 2.0.0
* asciidoctor-pdf alpha17
