= xref:rn-1_1_6.adoc[Release Notes - 1.1.6 - Talend Component Kit]
:page-partial:
:page-talend_skipindexation:

To get the full list of changes and bug fixes included in this new version, check the link:../main/1.1.6/changelog.html[changelogs].

== Component Kit Starter

The Component Kit Starter now allows to specify datasets and datastores. Since every input and output components must rely on a dataset and that each dataset requires a datastore, you need to make sure that your project complies with the applicable validation rules to build components properly.

== Enriching families with custom JAR and configuration

You can now enrich your component project with custom JAR and configuration without repackaging all applications.
You can specify this customization using the new `user.extensions.location` parameter of the component server.

== LocalConfiguration

You can now manually configure the `MaxBatchSize` property for a component or a component family. This is especially useful when testing your components.

== Dependencies updates

Several dependencies have been upgraded to a newer version, including:

* Talend UI 2.3.0
* Apache Meecrowave 1.2.6
* CXF 3.3.0
* Johnzon 1.1.11
* Apache Tomcat 9.0.16
