= Release Notes - 1.1.0 - Talend Component Kit
:page-partial:
:page-talend_skipindexation:

To get the full list of changes and bug fixes included in this new version, check the xref:changelog.adoc[changelogs].

== Output components

Output components can now only have one inbound connection.

== Datasets and datastores

Dataset and datastore internationalized names are now validated by the Maven and Gradle plugins of the Component Kit.

In addition, a validation rule now checks that each dataset corresponds to at least one source (input component) that does not require other parameters.

== Combined visibility conditions

It is now possible to combine several visibility conditions (`ActiveIfs`) using a unique operator (AND or OR).

In addition, `ActiveIf` now supports *CONTAINS* as evaluation strategy.

== Internationalization

Internalization now supports action names.

== Dependencies updates

Several dependencies have been upgraded to a newer version, including:

* CXF 3.2.6
* Apache Tomcat 9.0.12
* Log4j2 2.11.1
* Icons bundle 1.0.0
* Johnzon 1.1.9
* JUnit 5.3.1
* Meecrowave 1.2.4
* Netty 4.1.30.Final
* Xbean 4.10
* Beam 2.7.0
* Web UI bundle 1.0.2
* Apache Commons Compress 1.18
* Gradle 4.10.2 in Starter
